package cn.mutu.land.model;

// Generated 2017-2-12 21:29:15 by Hibernate Tools 4.0.0

/**
 * CostDetail generated by hbm2java
 */
public class CostDetail implements java.io.Serializable {

	private Integer id;
	private String xianMu;
	private String costDate;
	private String costType;
	private String costUse;
	private Double costMuch;
	private Double incomeMuch;
	private Double accountRemain;
	private String shouKuanRen;
	private String bz;
	private String dealStatus;

	public CostDetail() {
	}

	public CostDetail(String xianMu, String costDate, String costType,
			String costUse, Double costMuch, Double incomeMuch,
			Double accountRemain, String shouKuanRen, String bz,
			String dealStatus) {
		this.xianMu = xianMu;
		this.costDate = costDate;
		this.costType = costType;
		this.costUse = costUse;
		this.costMuch = costMuch;
		this.incomeMuch = incomeMuch;
		this.accountRemain = accountRemain;
		this.shouKuanRen = shouKuanRen;
		this.bz = bz;
		this.dealStatus = dealStatus;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getXianMu() {
		return this.xianMu;
	}

	public void setXianMu(String xianMu) {
		this.xianMu = xianMu;
	}

	public String getCostDate() {
		return this.costDate;
	}

	public void setCostDate(String costDate) {
		this.costDate = costDate;
	}

	public String getCostType() {
		return this.costType;
	}

	public void setCostType(String costType) {
		this.costType = costType;
	}

	public String getCostUse() {
		return this.costUse;
	}

	public void setCostUse(String costUse) {
		this.costUse = costUse;
	}

	public Double getCostMuch() {
		return this.costMuch;
	}

	public void setCostMuch(Double costMuch) {
		this.costMuch = costMuch;
	}

	public Double getIncomeMuch() {
		return this.incomeMuch;
	}

	public void setIncomeMuch(Double incomeMuch) {
		this.incomeMuch = incomeMuch;
	}

	public Double getAccountRemain() {
		return this.accountRemain;
	}

	public void setAccountRemain(Double accountRemain) {
		this.accountRemain = accountRemain;
	}

	public String getShouKuanRen() {
		return this.shouKuanRen;
	}

	public void setShouKuanRen(String shouKuanRen) {
		this.shouKuanRen = shouKuanRen;
	}

	public String getBz() {
		return this.bz;
	}

	public void setBz(String bz) {
		this.bz = bz;
	}

	public String getDealStatus() {
		return this.dealStatus;
	}

	public void setDealStatus(String dealStatus) {
		this.dealStatus = dealStatus;
	}

}
