package cn.mutu.land.model;

// Generated 2017-3-6 20:24:26 by Hibernate Tools 4.0.0

/**
 * EmployeeManagement generated by hbm2java
 */
public class EmployeeManagement implements java.io.Serializable {

	private int id;
	private Integer employeeId;
	private String employeeName;
	private Integer employeeAge;
	private String employeeDepart;
	private Integer employeePhone;
	private String employeeAddress;
	private String employeeJoinTime;
	private String employeeOutTime;
	private String bz;

	public EmployeeManagement() {
	}

	public EmployeeManagement(int id) {
		this.id = id;
	}

	public EmployeeManagement(int id, Integer employeeId, String employeeName,
			Integer employeeAge, String employeeDepart, Integer employeePhone,
			String employeeAddress, String employeeJoinTime,
			String employeeOutTime, String bz) {
		this.id = id;
		this.employeeId = employeeId;
		this.employeeName = employeeName;
		this.employeeAge = employeeAge;
		this.employeeDepart = employeeDepart;
		this.employeePhone = employeePhone;
		this.employeeAddress = employeeAddress;
		this.employeeJoinTime = employeeJoinTime;
		this.employeeOutTime = employeeOutTime;
		this.bz = bz;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Integer getEmployeeId() {
		return this.employeeId;
	}

	public void setEmployeeId(Integer employeeId) {
		this.employeeId = employeeId;
	}

	public String getEmployeeName() {
		return this.employeeName;
	}

	public void setEmployeeName(String employeeName) {
		this.employeeName = employeeName;
	}

	public Integer getEmployeeAge() {
		return this.employeeAge;
	}

	public void setEmployeeAge(Integer employeeAge) {
		this.employeeAge = employeeAge;
	}

	public String getEmployeeDepart() {
		return this.employeeDepart;
	}

	public void setEmployeeDepart(String employeeDepart) {
		this.employeeDepart = employeeDepart;
	}

	public Integer getEmployeePhone() {
		return this.employeePhone;
	}

	public void setEmployeePhone(Integer employeePhone) {
		this.employeePhone = employeePhone;
	}

	public String getEmployeeAddress() {
		return this.employeeAddress;
	}

	public void setEmployeeAddress(String employeeAddress) {
		this.employeeAddress = employeeAddress;
	}

	public String getEmployeeJoinTime() {
		return this.employeeJoinTime;
	}

	public void setEmployeeJoinTime(String employeeJoinTime) {
		this.employeeJoinTime = employeeJoinTime;
	}

	public String getEmployeeOutTime() {
		return this.employeeOutTime;
	}

	public void setEmployeeOutTime(String employeeOutTime) {
		this.employeeOutTime = employeeOutTime;
	}

	public String getBz() {
		return this.bz;
	}

	public void setBz(String bz) {
		this.bz = bz;
	}

}
