package cn.mutu.land.model;

// Generated 2017-3-6 20:24:26 by Hibernate Tools 4.0.0

/**
 * ProjectManagement generated by hbm2java
 */
public class ProjectManagement implements java.io.Serializable {

	private Integer id;
	private String proId;
	private String proName;
	private Double proMoney;
	private Double proIncome;
	private Double proRemain;
	private Double proCost;
	private Double proCostRemain;
	private String proZhuguan;
	private String proHezuo;
	private String proStartTime;
	private String proEndTime;
	private String proManager;
	private String proTeam;
	private String proBz;
	private String proApplication;
	private String proCheck;
	private String proStatus;

	public ProjectManagement() {
	}

	public ProjectManagement(String proId, String proName, Double proMoney,
			Double proIncome, Double proRemain, Double proCost,
			Double proCostRemain, String proZhuguan, String proHezuo,
			String proStartTime, String proEndTime, String proManager,
			String proTeam, String proBz, String proApplication,
			String proCheck, String proStatus) {
		this.proId = proId;
		this.proName = proName;
		this.proMoney = proMoney;
		this.proIncome = proIncome;
		this.proRemain = proRemain;
		this.proCost = proCost;
		this.proCostRemain = proCostRemain;
		this.proZhuguan = proZhuguan;
		this.proHezuo = proHezuo;
		this.proStartTime = proStartTime;
		this.proEndTime = proEndTime;
		this.proManager = proManager;
		this.proTeam = proTeam;
		this.proBz = proBz;
		this.proApplication = proApplication;
		this.proCheck = proCheck;
		this.proStatus = proStatus;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getProId() {
		return this.proId;
	}

	public void setProId(String proId) {
		this.proId = proId;
	}

	public String getProName() {
		return this.proName;
	}

	public void setProName(String proName) {
		this.proName = proName;
	}

	public Double getProMoney() {
		return this.proMoney;
	}

	public void setProMoney(Double proMoney) {
		this.proMoney = proMoney;
	}

	public Double getProIncome() {
		return this.proIncome;
	}

	public void setProIncome(Double proIncome) {
		this.proIncome = proIncome;
	}

	public Double getProRemain() {
		return this.proRemain;
	}

	public void setProRemain(Double proRemain) {
		this.proRemain = proRemain;
	}

	public Double getProCost() {
		return this.proCost;
	}

	public void setProCost(Double proCost) {
		this.proCost = proCost;
	}

	public Double getProCostRemain() {
		return this.proCostRemain;
	}

	public void setProCostRemain(Double proCostRemain) {
		this.proCostRemain = proCostRemain;
	}

	public String getProZhuguan() {
		return this.proZhuguan;
	}

	public void setProZhuguan(String proZhuguan) {
		this.proZhuguan = proZhuguan;
	}

	public String getProHezuo() {
		return this.proHezuo;
	}

	public void setProHezuo(String proHezuo) {
		this.proHezuo = proHezuo;
	}

	public String getProStartTime() {
		return this.proStartTime;
	}

	public void setProStartTime(String proStartTime) {
		this.proStartTime = proStartTime;
	}

	public String getProEndTime() {
		return this.proEndTime;
	}

	public void setProEndTime(String proEndTime) {
		this.proEndTime = proEndTime;
	}

	public String getProManager() {
		return this.proManager;
	}

	public void setProManager(String proManager) {
		this.proManager = proManager;
	}

	public String getProTeam() {
		return this.proTeam;
	}

	public void setProTeam(String proTeam) {
		this.proTeam = proTeam;
	}

	public String getProBz() {
		return this.proBz;
	}

	public void setProBz(String proBz) {
		this.proBz = proBz;
	}

	public String getProApplication() {
		return this.proApplication;
	}

	public void setProApplication(String proApplication) {
		this.proApplication = proApplication;
	}

	public String getProCheck() {
		return this.proCheck;
	}

	public void setProCheck(String proCheck) {
		this.proCheck = proCheck;
	}

	public String getProStatus() {
		return this.proStatus;
	}

	public void setProStatus(String proStatus) {
		this.proStatus = proStatus;
	}

}
