/*
 * File: app/store/baoXiaoTypeStore.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.store.baoXiaoTypeStore', {
    extend: 'Ext.data.Store',

    requires: [
        'Ext.data.field.Field'
    ],

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            storeId: 'baoXiaoTypeStore',
            data: [
                {
                    name: '差旅报销',
                    value: 'baoXiao_chailv'
                },
                {
                    name: '日常报销',
                    value: 'baoXiao_richang'
                },
                {
                    name: '借款',
                    value: 'baoXiao_jiekaun'
                },
                {
                    name: '还款',
                    value: 'baoXiao_huankaun'
                }
            ],
            fields: [
                {
                    name: 'name'
                },
                {
                    name: 'value'
                }
            ]
        }, cfg)]);
    }
});