/*
 * File: app/store/landKfqNow.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.store.landKfqNow', {
    extend: 'Ext.data.Store',

    requires: [
        'Ext.data.field.Field'
    ],

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            storeId: 'landKfqNow',
            data: [
                {
                    name: '用地现状统计',
                    value: 'xz'
                },
                {
                    name: '土地开发状况',
                    value: 'kf'
                },
                {
                    name: '土地供应状况',
                    value: 'gy'
                },
                {
                    name: '土地建成状况',
                    value: 'jc'
                },
                {
                    name: '土地利用结构',
                    value: 'jg'
                },
                {
                    name: '建筑工程状况',
                    value: 'gc'
                },
                {
                    name: '土地用地效益',
                    value: 'xy'
                },
                {
                    name: '土地管理绩效状况',
                    value: 'jx'
                }
            ],
            fields: [
                {
                    name: 'name'
                },
                {
                    name: 'value'
                }
            ]
        }, cfg)]);
    }
});