/*
 * File: app/store/landKfqSpTypeComboStore.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.store.landKfqSpTypeComboStore', {
    extend: 'Ext.data.Store',

    requires: [
        'Ext.data.field.Field'
    ],

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            storeId: 'landKfqSpTypeComboStore',
            data: [
                {
                    name: '经济技术开发区',
                    value: '1'
                },
                {
                    name: '高新技术产业开发区',
                    value: '2'
                },
                {
                    name: '保税区',
                    value: '3'
                },
                {
                    name: '出口加工区',
                    value: '4'
                },
                {
                    name: '边境经济合作区',
                    value: '5'
                },
                {
                    name: '其他类型的国家级开发区',
                    value: '6'
                },
                {
                    name: '省级经济开发区',
                    value: '7'
                },
                {
                    name: '省级高新技术产业园区',
                    value: '8'
                },
                {
                    name: '省级特色工业园区',
                    value: '9'
                }
            ],
            fields: [
                {
                    name: 'name'
                },
                {
                    name: 'value'
                }
            ]
        }, cfg)]);
    }
});