/*
 * File: app/model/costInfoModel.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.model.costInfoModel', {
    extend: 'Ext.data.Model',

    requires: [
        'Ext.data.field.Field'
    ],

    fields: [
        {
            name: 'id'
        },
        {
            name: 'proId'
        },
        {
            name: 'proName'
        },
        {
            name: 'proMoney'
        },
        {
            name: 'proIncome'
        },
        {
            name: 'proRemain'
        },
        {
            name: 'proCost'
        },
        {
            name: 'proCostRemain'
        },
        {
            name: 'proZhuguan'
        },
        {
            name: 'proHezuo'
        },
        {
            name: 'proStartTime'
        },
        {
            name: 'proEndTime'
        },
        {
            name: 'proManager'
        },
        {
            name: 'proTeam'
        },
        {
            name: 'proBz'
        },
        {
            name: 'proApplication'
        },
        {
            name: 'proCheck'
        },
        {
            name: 'proStatus'
        }
    ]
});