/*
 * File: app/model/landKfqTypeModel.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.model.landKfqTypeModel', {
    extend: 'Ext.data.Model',

    requires: [
        'Ext.data.field.Field'
    ],

    fields: [
        {
            name: 'id'
        },
        {
            name: 'calcName'
        },
        {
            name: 'calcDate'
        },
        {
            name: 'kfqType'
        },
        {
            name: 'kfqjb'
        },
        {
            name: 'kfqsplx'
        },
        {
            name: 'jcczzmj'
        },
        {
            name: 'gkcczmj'
        },
        {
            name: 'zzzmj'
        },
        {
            name: 'gkccRate'
        },
        {
            name: 'zzRate'
        },
        {
            name: 'ma'
        },
        {
            name: 'ma1'
        },
        {
            name: 'ma2'
        },
        {
            name: 'ma3'
        },
        {
            name: 'ma4'
        },
        {
            name: 'ma5'
        },
        {
            name: 'MA51'
        },
        {
            name: 'MA52'
        },
        {
            name: 'ma6'
        },
        {
            name: 'mb'
        },
        {
            name: 'MB1'
        },
        {
            name: 'MB11'
        },
        {
            name: 'MB12'
        },
        {
            name: 'MB2'
        },
        {
            name: 'MB21'
        },
        {
            name: 'MB22'
        },
        {
            name: 'mc'
        },
        {
            name: 'MC1'
        },
        {
            name: 'MC2'
        },
        {
            name: 'MC3'
        },
        {
            name: 'md'
        },
        {
            name: 'MD1'
        },
        {
            name: 'MD2'
        },
        {
            name: 'MD21'
        },
        {
            name: 'MD22'
        },
        {
            name: 'ME'
        },
        {
            name: 'ME1'
        },
        {
            name: 'ME2'
        },
        {
            name: 'ME21'
        },
        {
            name: 'ME22'
        },
        {
            name: 'mf'
        },
        {
            name: 'MG'
        },
        {
            name: 'MH'
        },
        {
            name: 'MH1'
        },
        {
            name: 'MH2'
        },
        {
            name: 'me'
        },
        {
            name: 'me21'
        },
        {
            name: 'de'
        },
        {
            name: 'dd'
        },
        {
            name: 'df'
        },
        {
            name: 'da'
        },
        {
            name: 'da2'
        },
        {
            name: 'da1'
        },
        {
            name: 'da3'
        },
        {
            name: 'da4'
        },
        {
            name: 'da5'
        },
        {
            name: 'da6'
        },
        {
            name: 'db'
        },
        {
            name: 'dc'
        }
    ]
});