/*
 * File: app/view/baoXiao_richang.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.baoXiao_richang', {
    extend: 'Ext.window.Window',
    alias: 'widget.baoXiao_richang',

    requires: [
        'MyApp.view.db_RightInfoAddWindowViewModel4',
        'Ext.form.Panel',
        'Ext.form.FieldSet',
        'Ext.form.field.ComboBox',
        'Ext.form.field.Display',
        'Ext.form.field.Number',
        'Ext.form.Label',
        'Ext.toolbar.Toolbar',
        'Ext.button.Button',
        'Ext.toolbar.Fill',
        'Ext.toolbar.Spacer',
        'Ext.form.field.Hidden'
    ],

    viewModel: {
        type: 'baoxiao_richang'
    },
    height: 597,
    id: 'baoXiao_richang',
    width: 630,
    layout: 'fit',
    title: '差旅报销申请单',
    titleAlign: 'center',
    defaultListenerScope: true,

    items: [
        {
            xtype: 'form',
            id: 'baoXiao_chailvForm1',
            layout: 'auto',
            bodyPadding: 10,
            jsonSubmit: true,
            url: 'add_ProjectInfo',
            items: [
                {
                    xtype: 'fieldset',
                    height: 87,
                    width: 615,
                    layout: 'absolute',
                    title: '',
                    items: [
                        {
                            xtype: 'combobox',
                            x: 0,
                            y: 10,
                            width: 400,
                            fieldLabel: '选择报销项目',
                            labelWidth: 90,
                            name: 'projectName',
                            readOnly: false,
                            allowBlank: false,
                            displayField: 'proName',
                            store: 'projectInfoStore'
                        },
                        {
                            xtype: 'combobox',
                            x: 0,
                            y: 50,
                            id: 'applyUser1',
                            width: 230,
                            fieldLabel: '报销申请人',
                            labelWidth: 90,
                            name: 'applyUser',
                            readOnly: false,
                            allowBlank: false,
                            displayField: 'trueName',
                            store: 'uUserInfoStore'
                        },
                        {
                            xtype: 'combobox',
                            x: 250,
                            y: 50,
                            width: 180,
                            fieldLabel: '选择部门',
                            labelWidth: 70,
                            name: 'departName',
                            readOnly: false,
                            allowBlank: false,
                            displayField: 'deptName',
                            store: 'uDeptInfoStore'
                        },
                        {
                            xtype: 'displayfield',
                            x: 410,
                            y: 10,
                            id: 'proCostRemain1',
                            width: 180,
                            fieldLabel: '项目可用资金',
                            labelWidth: 90
                        }
                    ]
                },
                {
                    xtype: 'fieldset',
                    height: 381,
                    width: 615,
                    layout: 'absolute',
                    title: '日常报销费用明细',
                    items: [
                        {
                            xtype: 'fieldset',
                            y: 20,
                            height: 270,
                            padding: '0,0,0,0',
                            width: 390,
                            title: '',
                            items: [
                                {
                                    xtype: 'fieldset',
                                    margin: '0,0,0,0',
                                    padding: '5,0,5,0',
                                    width: 398,
                                    layout: {
                                        type: 'table',
                                        columns: 2
                                    },
                                    items: [
                                        {
                                            xtype: 'numberfield',
                                            width: 120,
                                            labelWidth: 170,
                                            hideTrigger: true,
                                            minValue: 0
                                        },
                                        {
                                            xtype: 'numberfield',
                                            width: 50,
                                            hideTrigger: true,
                                            minValue: 0
                                        },
                                        {
                                            xtype: 'numberfield',
                                            width: 119,
                                            name: 'clAimTaxi',
                                            hideTrigger: true
                                        },
                                        {
                                            xtype: 'numberfield',
                                            width: 230,
                                            fieldLabel: '差旅地住宿费',
                                            labelWidth: 170,
                                            hideTrigger: true,
                                            minValue: 0
                                        },
                                        {
                                            xtype: 'numberfield',
                                            width: 120,
                                            name: 'clAimHotel',
                                            hideTrigger: true
                                        },
                                        {
                                            xtype: 'numberfield',
                                            width: 230,
                                            fieldLabel: '差旅地餐饮费',
                                            labelWidth: 170,
                                            hideTrigger: true,
                                            minValue: 0
                                        },
                                        {
                                            xtype: 'numberfield',
                                            width: 120,
                                            name: 'clAimFood',
                                            hideTrigger: true
                                        },
                                        {
                                            xtype: 'numberfield',
                                            margin: '0,0,0,0',
                                            width: 230,
                                            fieldLabel: '差旅地其他费用',
                                            labelWidth: 170,
                                            hideTrigger: true,
                                            minValue: 0
                                        },
                                        {
                                            xtype: 'numberfield',
                                            margin: '0,0,0,0',
                                            width: 120,
                                            name: 'clAimOther',
                                            hideTrigger: true
                                        }
                                    ]
                                },
                                {
                                    xtype: 'fieldset',
                                    margin: '0,0,0,0',
                                    padding: '5,0,5,0',
                                    width: '',
                                    title: '',
                                    layout: {
                                        type: 'table',
                                        columns: 2
                                    },
                                    items: [
                                        {
                                            xtype: 'numberfield',
                                            width: 230,
                                            fieldLabel: '返程市内交通费',
                                            labelWidth: 170,
                                            hideTrigger: true,
                                            minValue: 0
                                        },
                                        {
                                            xtype: 'numberfield',
                                            width: 120,
                                            name: 'clBackTaxi',
                                            emptyText: ' ',
                                            hideTrigger: true
                                        },
                                        {
                                            xtype: 'numberfield',
                                            margin: '0,0,0,0',
                                            width: 230,
                                            fieldLabel: '返程长途交通费',
                                            labelWidth: 170,
                                            name: '',
                                            hideTrigger: true,
                                            minValue: 0
                                        },
                                        {
                                            xtype: 'numberfield',
                                            margin: '0,0,0,0',
                                            width: 120,
                                            name: 'clBackTrain',
                                            hideTrigger: true
                                        }
                                    ]
                                }
                            ]
                        },
                        {
                            xtype: 'fieldset',
                            x: 0,
                            y: 310,
                            margin: '0,0,0,0',
                            padding: '5,0,5,0',
                            width: 390,
                            layout: {
                                type: 'table',
                                columns: 2
                            },
                            items: [
                                {
                                    xtype: 'numberfield',
                                    margin: '0,0,0,0',
                                    width: 230,
                                    fieldLabel: '合计（发票）费用',
                                    labelWidth: 170,
                                    name: 'clFapiao',
                                    editable: false,
                                    hideTrigger: true,
                                    minValue: 0
                                },
                                {
                                    xtype: 'numberfield',
                                    id: 'clBaoxiao1',
                                    margin: '0,0,0,0',
                                    width: 120,
                                    name: 'clBaoxiao',
                                    editable: false,
                                    hideTrigger: true
                                }
                            ]
                        },
                        {
                            xtype: 'label',
                            x: 50,
                            y: 0,
                            text: '费用类别'
                        },
                        {
                            xtype: 'label',
                            x: 190,
                            y: 0,
                            text: '票据数'
                        },
                        {
                            xtype: 'label',
                            x: 270,
                            y: 0,
                            text: '金额（元）'
                        },
                        {
                            xtype: 'fieldset',
                            x: 400,
                            y: 20,
                            height: 110,
                            width: 183,
                            title: '借还款',
                            items: [
                                {
                                    xtype: 'numberfield',
                                    margin: '0,0,0,0',
                                    width: 150,
                                    fieldLabel: '个人欠款',
                                    labelWidth: 60,
                                    editable: false,
                                    emptyText: '0',
                                    hideTrigger: true,
                                    minValue: 0
                                },
                                {
                                    xtype: 'numberfield',
                                    margin: '0,0,0,0',
                                    width: 150,
                                    fieldLabel: '本次还款',
                                    labelWidth: 60,
                                    name: 'clHuankuan',
                                    editable: false,
                                    emptyText: '0',
                                    hideTrigger: true,
                                    minValue: 0
                                },
                                {
                                    xtype: 'numberfield',
                                    margin: '0,0,0,0',
                                    width: 150,
                                    fieldLabel: '借款剩余',
                                    labelWidth: 60,
                                    editable: false,
                                    emptyText: '0',
                                    hideTrigger: true,
                                    minValue: 0
                                }
                            ]
                        },
                        {
                            xtype: 'toolbar',
                            x: 400,
                            y: 310,
                            width: 86,
                            items: [
                                {
                                    xtype: 'button',
                                    text: '汇总计算'
                                }
                            ]
                        }
                    ]
                }
            ],
            dockedItems: [
                {
                    xtype: 'toolbar',
                    dock: 'bottom',
                    items: [
                        {
                            xtype: 'tbfill'
                        },
                        {
                            xtype: 'button',
                            text: '取消关闭',
                            listeners: {
                                click: 'onButtonClick1'
                            }
                        },
                        {
                            xtype: 'tbspacer',
                            width: 30
                        },
                        {
                            xtype: 'button',
                            text: '确认提交',
                            listeners: {
                                click: 'onButtonClick'
                            }
                        },
                        {
                            xtype: 'hiddenfield',
                            fieldLabel: 'Label',
                            name: 'costType',
                            value: '差旅报销'
                        },
                        {
                            xtype: 'hiddenfield',
                            id: 'costDescript1',
                            fieldLabel: 'Label',
                            name: 'costDescript',
                            value: '差旅报销'
                        }
                    ]
                }
            ],
            listeners: {
                afterrender: 'onDb_projectInfoAddWindowFormAfterRender'
            }
        }
    ],

    onButtonClick1: function(button, e, eOpts) {
        var win = Ext.getCmp('baoXiao_chailv');
        win.close();
    },

    onButtonClick: function(button, e, eOpts) {
        var applyUser = Ext.getCmp('applyUser').getValue();
        var clAim = Ext.getCmp('clAim').getValue();
        var cl_start = Ext.getCmp('clStart').getValue().substring(0,10);
        var cl_end = Ext.getCmp('clEnd').getValue().substring(0,10);
        Ext.getCmp('costDescript').setValue("报销"+applyUser+cl_start+"至"+cl_end+clAim+"差旅费用");
        var win = Ext.getCmp('baoXiao_chailv');
        var myform = Ext.getCmp('baoXiao_chailvForm');

        if (myform.isValid())
        {

            myform.submit({
                //url : 'add_ProjectInfo',
                success : function (form, action)
                {
                    Ext.Msg.alert('成功', '提交成功');

                    var mystore = Ext.StoreMgr.get('costInfoStore'); //获得store对象
                    mystore.reload();
                    win.close();
                },
                failure: function(form, action){
                    Ext.Msg.alert('失败', '提交失败');
                    win.close();
                }
            });
        }
        else{
            Ext.Msg.alert('注意', '填写的信息有误，请检查！');
        }

        return;
    },

    onDb_projectInfoAddWindowFormAfterRender: function(component, eOpts) {
        //获取当前注册时间
        var registerdateField = Ext.getCmp('proId');
        var dateStr = "";
        var myDate = new Date();
        dateStr += myDate.getFullYear();    //获取完整的年份(4位,1970-????)
        dateStr += (myDate.getMonth()+1);       //获取当前月份(0-11,0代表1月)
        dateStr += myDate.getDate(); //获取当前日(1-31)
        dateStr += myDate.getHours();
        dateStr += myDate.getMinutes();

        registerdateField.setValue(dateStr);
    }

});