/*
 * File: app/view/db_projectInfoAddWindow.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.db_projectInfoAddWindow', {
    extend: 'Ext.window.Window',
    alias: 'widget.db_projectInfoAddWindow',

    requires: [
        'MyApp.view.db_RightInfoAddWindowViewModel1',
        'Ext.form.Panel',
        'Ext.form.FieldSet',
        'Ext.form.field.Number',
        'Ext.form.field.Date',
        'Ext.form.field.ComboBox',
        'Ext.form.field.HtmlEditor',
        'Ext.form.field.Hidden',
        'Ext.toolbar.Toolbar',
        'Ext.toolbar.Fill',
        'Ext.button.Button',
        'Ext.toolbar.Spacer'
    ],

    viewModel: {
        type: 'db_projectinfoaddwindow'
    },
    height: 629,
    id: 'db_projectInfoAddWindow',
    width: 630,
    layout: 'fit',
    title: '项目申请',
    defaultListenerScope: true,

    items: [
        {
            xtype: 'form',
            id: 'db_projectInfoAddWindowForm',
            layout: 'auto',
            bodyPadding: 10,
            jsonSubmit: true,
            url: 'add_ProjectInfo',
            items: [
                {
                    xtype: 'fieldset',
                    width: 615,
                    title: '项目基本信息',
                    items: [
                        {
                            xtype: 'textfield',
                            id: 'proName',
                            width: 400,
                            fieldLabel: '填写项目名称',
                            labelWidth: 90,
                            name: 'proName',
                            readOnly: false,
                            allowBlank: false
                        },
                        {
                            xtype: 'textfield',
                            id: 'proId',
                            width: 400,
                            fieldLabel: '填写项目编号',
                            labelWidth: 90,
                            name: 'proId',
                            readOnly: false,
                            allowBlank: false
                        }
                    ]
                },
                {
                    xtype: 'fieldset',
                    height: 449,
                    width: 615,
                    title: '项目详细信息',
                    items: [
                        {
                            xtype: 'numberfield',
                            id: 'proMoney',
                            width: 400,
                            fieldLabel: '项目金额',
                            labelWidth: 70,
                            name: 'proMoney',
                            allowBlank: false,
                            emptyText: '0',
                            validateBlank: true
                        },
                        {
                            xtype: 'numberfield',
                            id: 'proIncome',
                            width: 400,
                            fieldLabel: '到账金额',
                            labelWidth: 70,
                            name: 'proIncome',
                            emptyText: '0',
                            validateBlank: true
                        },
                        {
                            xtype: 'numberfield',
                            hidden: true,
                            id: 'proRemain',
                            width: 400,
                            fieldLabel: '剩余金额',
                            labelWidth: 70,
                            name: 'proRemain',
                            readOnly: false,
                            editable: false,
                            emptyText: '0',
                            validateBlank: true
                        },
                        {
                            xtype: 'textfield',
                            width: 400,
                            fieldLabel: '主管单位',
                            labelWidth: 70,
                            name: 'proZhuguan',
                            allowBlank: false,
                            validateBlank: true
                        },
                        {
                            xtype: 'textfield',
                            width: 400,
                            fieldLabel: '合作单位',
                            labelWidth: 70,
                            name: 'proHezuo',
                            validateBlank: true
                        },
                        {
                            xtype: 'datefield',
                            width: 400,
                            fieldLabel: '开始时间',
                            labelWidth: 70,
                            name: 'proStartTime',
                            allowBlank: false,
                            validateBlank: true,
                            format: 'Y-m-d'
                        },
                        {
                            xtype: 'datefield',
                            width: 400,
                            fieldLabel: '结束时间',
                            labelWidth: 70,
                            name: 'proEndTime',
                            allowBlank: false,
                            validateBlank: true,
                            format: 'Y-m-d'
                        },
                        {
                            xtype: 'combobox',
                            width: 400,
                            fieldLabel: '项目经理',
                            labelWidth: 70,
                            name: 'proManager',
                            allowBlank: false,
                            validateBlank: true,
                            displayField: 'trueName',
                            store: 'uUserInfoStore'
                        },
                        {
                            xtype: 'textfield',
                            width: 400,
                            fieldLabel: '参与人员',
                            labelWidth: 70,
                            name: 'proTeam',
                            validateBlank: true
                        },
                        {
                            xtype: 'htmleditor',
                            height: 136,
                            fieldLabel: '项目简介',
                            labelWidth: 70,
                            name: 'proBz'
                        },
                        {
                            xtype: 'hiddenfield',
                            anchor: '100%',
                            fieldLabel: 'Label',
                            name: 'proStatus'
                        },
                        {
                            xtype: 'hiddenfield',
                            anchor: '100%',
                            fieldLabel: 'Label',
                            name: 'proApplication'
                        },
                        {
                            xtype: 'hiddenfield',
                            anchor: '100%',
                            fieldLabel: 'Label',
                            name: 'id'
                        }
                    ]
                }
            ],
            dockedItems: [
                {
                    xtype: 'toolbar',
                    dock: 'bottom',
                    items: [
                        {
                            xtype: 'tbfill'
                        },
                        {
                            xtype: 'button',
                            text: '取消关闭',
                            listeners: {
                                click: 'onButtonClick1'
                            }
                        },
                        {
                            xtype: 'tbspacer',
                            width: 30
                        },
                        {
                            xtype: 'button',
                            text: '确认提交',
                            listeners: {
                                click: 'onButtonClick'
                            }
                        }
                    ]
                }
            ],
            listeners: {
                afterrender: 'onDb_projectInfoAddWindowFormAfterRender'
            }
        }
    ],

    onButtonClick1: function(button, e, eOpts) {
        var win = Ext.getCmp('db_projectInfoAddWindow');
        win.close();
    },

    onButtonClick: function(button, e, eOpts) {
        var win = Ext.getCmp('db_projectInfoAddWindow');
        var myform = Ext.getCmp('db_projectInfoAddWindowForm');

        if (myform.isValid())
        {

            myform.submit({
                //url : 'add_ProjectInfo',
                success : function (form, action)
                {
                    Ext.Msg.alert('成功', '提交成功');

                    var mystore = Ext.StoreMgr.get('projectInfoStore'); //获得store对象
                    mystore.reload();
                    win.close();
                },
                failure: function(form, action){
                    Ext.Msg.alert('失败', '提交失败');
                    win.close();
                }
            });
        }
        else{
            Ext.Msg.alert('注意', '填写的信息有误，请检查！');
        }

        return;
    },

    onDb_projectInfoAddWindowFormAfterRender: function(component, eOpts) {
        //获取当前注册时间
        var registerdateField = Ext.getCmp('proId');
        var dateStr = "";
        var myDate = new Date();
        dateStr += myDate.getFullYear();    //获取完整的年份(4位,1970-????)
        dateStr += (myDate.getMonth()+1);       //获取当前月份(0-11,0代表1月)
        dateStr += myDate.getDate(); //获取当前日(1-31)
        dateStr += myDate.getHours();
        dateStr += myDate.getMinutes();

        registerdateField.setValue(dateStr);
    }

});