/*
 * File: app/view/enterprise_kfqIntensity.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.enterprise_kfqIntensity', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.enterprise_kfqIntensity',

    requires: [
        'Ext.grid.Panel',
        'Ext.grid.column.RowNumberer',
        'Ext.grid.column.Number',
        'Ext.grid.View',
        'Ext.toolbar.Toolbar',
        'Ext.form.field.Text',
        'Ext.button.Button',
        'Ext.toolbar.Separator'
    ],

    height: 588,
    width: 924,
    layout: 'border',
    title: '',
    defaultListenerScope: true,

    items: [
        {
            xtype: 'gridpanel',
            region: 'center',
            autoScroll: true,
            id: 'monitor_Value_Gird',
            title: '开发区集约度分值计算数据',
            store: 'landIndexIntensityValueStore',
            columns: [
                {
                    xtype: 'rownumberer'
                },
                {
                    xtype: 'gridcolumn',
                    hidden: true,
                    width: 130,
                    dataIndex: 'projectId',
                    text: '评价编号'
                },
                {
                    xtype: 'gridcolumn',
                    width: 100,
                    dataIndex: 'kfqName',
                    text: '开发区名称'
                },
                {
                    xtype: 'gridcolumn',
                    width: 150,
                    dataIndex: 'kfqType',
                    text: '开发区类型'
                },
                {
                    xtype: 'numbercolumn',
                    width: 150,
                    dataIndex: 'mainArea',
                    text: '主区',
                    format: '0,000.000'
                },
                {
                    xtype: 'numbercolumn',
                    width: 130,
                    dataIndex: 'mainLanduse',
                    text: '土地利用状况',
                    format: '0,000.000'
                },
                {
                    xtype: 'numbercolumn',
                    dataIndex: 'mainLanduseDegree',
                    text: '土地利用程度',
                    format: '0,000.000'
                },
                {
                    xtype: 'numbercolumn',
                    width: 120,
                    dataIndex: 'mainLanduseDegreeSupply',
                    text: '土地供应率',
                    format: '0,000.000'
                },
                {
                    xtype: 'numbercolumn',
                    dataIndex: 'mainLanduseDegreeBuild',
                    text: '土地建成率',
                    format: '0,000.000'
                },
                {
                    xtype: 'numbercolumn',
                    dataIndex: 'mainLanduseConstruct',
                    text: '用地结构状况',
                    format: '0,000.000'
                },
                {
                    xtype: 'numbercolumn',
                    dataIndex: 'mainLanduseConstructIndustry',
                    text: '工业用地率',
                    format: '0,000.000'
                },
                {
                    xtype: 'numbercolumn',
                    dataIndex: 'mainLanduseIntensity',
                    text: '土地利用强度',
                    format: '0,000.000'
                },
                {
                    xtype: 'numbercolumn',
                    dataIndex: 'mainLanduseIntensityRatio',
                    text: '综合容积率',
                    format: '0,000.000'
                },
                {
                    xtype: 'numbercolumn',
                    dataIndex: 'mainLanduseIntensityDensity',
                    text: '建筑密度',
                    format: '0,000.000'
                },
                {
                    xtype: 'numbercolumn',
                    dataIndex: 'mainLanduseIntensitySumratio',
                    text: '工业用地综合容积率',
                    format: '0,000.000'
                },
                {
                    xtype: 'numbercolumn',
                    dataIndex: 'mainLanduseIntensityBuildindex',
                    text: '工业用地建筑系数',
                    format: '0,000.000'
                },
                {
                    xtype: 'numbercolumn',
                    dataIndex: 'mainBenefit',
                    text: '用地效益',
                    format: '0,000.000'
                },
                {
                    xtype: 'numbercolumn',
                    dataIndex: 'mainBenefitInexport',
                    text: '产业用地投入产出效益',
                    format: '0,000.000'
                },
                {
                    xtype: 'numbercolumn',
                    dataIndex: 'mainBenefitInexportAssets',
                    text: '工业用地固定资产投入强度',
                    format: '0,000.000'
                },
                {
                    xtype: 'numbercolumn',
                    dataIndex: 'mainBenefitInexportPopulation',
                    text: '工业用地地均税收',
                    format: '0,000.000'
                },
                {
                    xtype: 'numbercolumn',
                    dataIndex: 'mainPerformance',
                    text: '管理绩效',
                    format: '0,000.000'
                },
                {
                    xtype: 'numbercolumn',
                    dataIndex: 'mainPerformanceManage',
                    text: '土地利用监管绩效',
                    format: '0,000.000'
                },
                {
                    xtype: 'numbercolumn',
                    dataIndex: 'mainPerformanceManageIdle',
                    text: '土地闲置率',
                    format: '0,000.000'
                }
            ],
            dockedItems: [
                {
                    xtype: 'toolbar',
                    dock: 'top',
                    items: [
                        {
                            xtype: 'textfield',
                            id: 'land_KfqName_SearchText',
                            listeners: {
                                change: 'onLand_KfqName_SearchTextChange'
                            }
                        },
                        {
                            xtype: 'button',
                            hidden: true,
                            icon: 'images/table/search.png',
                            text: '查询',
                            listeners: {
                                click: 'onButtonClick4'
                            }
                        },
                        {
                            xtype: 'tbseparator'
                        },
                        {
                            xtype: 'button',
                            icon: 'images/table/preview1.png',
                            text: '查看',
                            listeners: {
                                click: 'onButtonClick21'
                            }
                        },
                        {
                            xtype: 'button',
                            icon: 'images/table/delete.png',
                            text: '删除',
                            listeners: {
                                click: 'onButtonClick31'
                            }
                        }
                    ]
                }
            ]
        }
    ],

    onLand_KfqName_SearchTextChange: function(field, newValue, oldValue, eOpts) {
        //var searchKeyword = Ext.getCmp('land_KfqName_SearchText').getValue();
        var mystore = Ext.StoreMgr.get('landIndexIntensityValueStore'); //获得store对象
        //在load事件中添加参数
        mystore.load({
            params :{searchKeyword : newValue}
        });
    },

    onButtonClick4: function(button, e, eOpts) {
        var searchKeyword = Ext.getCmp('land_KfqName_SearchText').getValue();
        var mystore = Ext.StoreMgr.get('landIndexIntensityValueStore'); //获得store对象
        //在load事件中添加参数
        mystore.load({
            params :{searchKeyword : searchKeyword}
        });
    },

    onButtonClick21: function(button, e, eOpts) {
        //获取数据
        var models = Ext.getCmp('monitor_Value_Gird').getSelection();
        if (models.length === 0){
            Ext.Msg.alert('提示', '请选择一条数据后再查看信息。');
            return;
        } else if(models.length >1){
            Ext.Msg.alert('提示', '每次只能查看一条信息，请重新选择。');
            return;
        }

        //启动窗口
        var win = Ext.widget('enterprise_IntensityScoreCheck');
        win.setTitle('查看');
        win.show();
        Ext.getCmp('intensity_value_kfqAreaText1').setValue(models[0].get('kfqName'));
        var kfqType = models[0].get('kfqType');
        var formId;
        if(kfqType.indexOf('工业')>=0){
            Ext.getCmp('intensity_value_tabPanel1').setActiveTab('indensity_value_industryTab1');
            formId = 'intensity_value_industryForm1';
        }else{
            Ext.getCmp('intensity_value_tabPanel1').setActiveTab('indensity_value_cityTab1');
            formId= 'intensity_value_cityForm1';
        }
        Ext.getCmp('intensity_value_activeFormId1').setValue(formId);
        var form = Ext.getCmp(formId).getForm();
        form.loadRecord(models[0]);



    },

    onButtonClick31: function(button, e, eOpts) {
        //获取数据
        var records = Ext.getCmp('monitor_Value_Gird').getSelection();
        if (records.length === 0){
           Ext.Msg.alert('提示', '请选择一条数据后再点击删除按钮。');
           return;
        }
        var  ids =new Array(records.length);
        for(var i = 0;i<records.length;i++){
            ids[i] = records[i].get("id");
        }
        if(ids.length ==1){
            Ext.Msg.confirm('提示', '您正在删除：<br/>[' + records[0].get('kfqName') +']<br/> 确认删除？', getResult);
        }else{
            Ext.Msg.confirm('提示', '您正在删除<br/>[' +ids.length+']组数据。<br/> 确认删除？', getResult);
        }


        function getResult(confirm)
        {
            console.log('confirm:', confirm);
            if (confirm == "yes"){
                Ext.Ajax.request(
                {
                    url : 'del_indexWeight',
                    params :
                    {
                        ids : ids
                    },
                    success : function (response){
                        Ext.Msg.alert('成功提示', '记录删除成功。');
                        var mystore = Ext.StoreMgr.get('landIndexIntensityValueStore');
                        mystore.load();
                    },
                    failure : function (response){
                        Ext.Msg.alert('失败提示', '记录删除失败。');
                    }
                });
            }
        }
    }

});