/*
 * File: app/view/enterprise_uploadMapCheckResultWindow.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.enterprise_uploadMapCheckResultWindow', {
    extend: 'Ext.window.Window',
    alias: 'widget.enterprise_uploadMapCheckResultWindow',

    requires: [
        'Ext.form.Panel',
        'Ext.form.field.TextArea',
        'Ext.form.field.Hidden',
        'Ext.toolbar.Toolbar',
        'Ext.toolbar.Fill',
        'Ext.button.Button'
    ],

    height: 188,
    id: 'enterprise_uploadMapCheckResultWindow',
    width: 445,
    layout: 'fit',
    title: '审核结果',
    defaultListenerScope: true,

    items: [
        {
            xtype: 'form',
            id: 'system_MapAddForm1',
            modelValidation: false,
            bodyPadding: 10,
            jsonSubmit: true,
            url: 'update_unshPass',
            items: [
                {
                    xtype: 'textareafield',
                    anchor: '100%',
                    height: 100,
                    id: 'ent_uploadInfoCheckRestlField',
                    fieldLabel: '审核批语',
                    labelAlign: 'right',
                    labelWidth: 80,
                    name: 'bz'
                },
                {
                    xtype: 'hiddenfield',
                    anchor: '100%',
                    id: 'checkId',
                    fieldLabel: 'Label',
                    name: 'id'
                }
            ],
            dockedItems: [
                {
                    xtype: 'toolbar',
                    dock: 'bottom',
                    items: [
                        {
                            xtype: 'tbfill'
                        },
                        {
                            xtype: 'button',
                            text: '取消',
                            listeners: {
                                click: 'onButtonClick1'
                            }
                        },
                        {
                            xtype: 'button',
                            text: '确定',
                            listeners: {
                                click: 'onButtonClick'
                            }
                        }
                    ]
                }
            ]
        }
    ],

    onButtonClick1: function(button, e, eOpts) {
        var win  = Ext.getCmp('enterprise_uploadMapCheckResultWindow');
        win.close();
    },

    onButtonClick: function(button, e, eOpts) {
        // Ext.Msg.confirm('提示',' 确认提交？注:提交成功后不可更改!', getResult);
        //                         function getResult(confirm)
        //                         {
        //   console.log('confirm:', confirm);

        //  if (confirm == "yes"){
        var grid = Ext.getCmp('zdxx_uncheck');
        var records = grid.getSelection();
        console.log("record:",records);
        var id =records[0].get("id");
        var shbz = Ext.getCmp('ent_uploadInfoCheckRestlField').getValue();
        console.log(shbz);

        Ext.Ajax.request({
            url: 'update_shPass',
            params: {
                "id": id,
                "isPass": 5,
                "bz":shbz
            },
            success: function() {
                Ext.Msg.alert('成功', '操作成功，宗地信息已驳回！');
                grid.getStore().reload();
                console.log("store1:",grid.getStore());
                console.log(grid.getStore().getCount());

                var mystore = Ext.StoreMgr.get('zd_checkStore');
                console.log("mystore:",mystore);
                console.log(mystore.getCount());
                // var record = store.findRecord('isPass',isPass);
                // console.log(record);
                // var dm = record.get('dldm');
                // console.log(dm);


                //        var status =records[0].get("isPass");
                //         console.log("status:",status);
                var win = Ext.getCmp('kfq_managesh');
                win.close();
                var win1 = Ext.getCmp('enterprise_uploadMapCheckResultWindow');
                win1.close();


            },
            failure: function() {
                Ext.Msg.alert('失败', '审核失败，可能由网络问题造成，请刷新重试。');
            }
        });//}}

    }

});