/*
 * File: app/view/kfq_uploadDataCheck.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.kfq_uploadDataCheck', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.kfq_uploadDataCheck',

    requires: [
        'MyApp.view.business_uploadMapViewModel1',
        'Ext.tab.Panel',
        'Ext.tab.Tab',
        'Ext.grid.Panel',
        'Ext.grid.column.RowNumberer',
        'Ext.grid.column.Action',
        'Ext.grid.View',
        'Ext.selection.CheckboxModel',
        'Ext.toolbar.Toolbar',
        'Ext.form.field.ComboBox'
    ],

    viewModel: {
        type: 'kfq_uploaddatacheck'
    },
    autoScroll: true,
    height: 675,
    width: 879,
    layout: 'border',
    title: '上报数据审核',
    defaultListenerScope: true,

    items: [
        {
            xtype: 'tabpanel',
            region: 'center',
            activeTab: 0,
            items: [
                {
                    xtype: 'panel',
                    layout: 'border',
                    title: '未审核',
                    items: [
                        {
                            xtype: 'gridpanel',
                            region: 'center',
                            id: 'zdxx_uncheck',
                            title: '',
                            sortableColumns: false,
                            store: 'costInfoStore',
                            columns: [
                                {
                                    xtype: 'rownumberer',
                                    width: 66,
                                    dataIndex: 'zdId',
                                    text: '序号'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    width: 80,
                                    dataIndex: 'proName',
                                    text: '填报年份'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'proCost',
                                    text: '开发区名称'
                                },
                                {
                                    xtype: 'actioncolumn',
                                    handler: function(view, rowIndex, colIndex, item, e, record, row) {
                                        if (colIndex === undefined || colIndex < 2) {
                                            return;
                                        }
                                        if(record.get('ismap')===1){
                                            var filepath=record.get('filePath');
                                            var index=filepath.lastIndexOf('/');
                                            if(index<=0){
                                                Ext.Msg.alert('提示','解析文件路径出错');
                                            }else{
                                                var filename=filepath.substring(index+1);
                                                filepath=filepath.substr(0,index)+'/';
                                                var nwin = window.open();
                                                var href="public/mapUpload/shppreview.html?filepath="+filepath+"&filename="+filename;
                                                nwin.location=href;
                                            }
                                        }else Ext.Msg.alert('提示','未上传图形数据');
                                    },
                                    align: 'center',
                                    dataIndex: 'proCost',
                                    text: '查看图斑',
                                    icon: 'images/table/preview1.png'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'proZhuguan',
                                    text: '开发区评价范围'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'proHezuo',
                                    text: '开发区评价类型'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'proStartTime',
                                    text: '图斑编号'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'proEndTime',
                                    text: '地类名称'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'proManager',
                                    text: '地类代码'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'proTeam',
                                    text: '地类面积'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'proApplication',
                                    text: '权属'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'proCheck',
                                    text: '供应时间'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'proStatus',
                                    text: '供应类型'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'gydm',
                                    text: '供应代码'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'tdzpg',
                                    text: '土地招拍佳情况'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'synx',
                                    text: '使用年限'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'tdsyz',
                                    text: '土地使用者'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'jzmj',
                                    text: '建筑面积(平方米)'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'jzjdmj',
                                    text: '建筑基地面积(平方米)'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'jdzmj',
                                    text: '建筑物、构筑物基底及露天堆场、露天操作场地的总面积（平方米）'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'gxlb',
                                    text: '高新技术产业用地类别'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'gxydmj',
                                    text: '高新技术产业用地面积(公顷）'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'gxzsbl',
                                    text: '高新技术产业用地面积折算比例 '
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'gxsr',
                                    text: '高新技术产业收入（万元）'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'gxss',
                                    text: '高新技术产业税收（万元）'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'ghyt',
                                    text: '规划用途'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'pzyt',
                                    text: '批准用途'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'proBz',
                                    text: '土地闲置情况'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'rdyj',
                                    text: '认定依据'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'gdzctzze',
                                    text: '工业企业、工业物流企业固定资产投资总额(万元）'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'esssze',
                                    text: '二、三产业税收总额（万元/年）'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'qyzsr',
                                    text: '工业企业工业物流企业总收入（万元/年）'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'check',
                                    text: '工业企业工业物流企业税收总额（万元/年）'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'bz',
                                    text: '备注'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'isPass',
                                    text: '状态'
                                }
                            ],
                            selModel: {
                                selType: 'checkboxmodel'
                            }
                        }
                    ],
                    listeners: {
                        activate: 'onPanelActivate'
                    }
                },
                {
                    xtype: 'panel',
                    layout: 'border',
                    title: '已审核通过',
                    items: [
                        {
                            xtype: 'gridpanel',
                            region: 'center',
                            id: 'zdxx_pass',
                            title: '',
                            sortableColumns: false,
                            store: 'costInfoStore',
                            columns: [
                                {
                                    xtype: 'rownumberer',
                                    width: 66,
                                    dataIndex: 'zdId',
                                    text: '序号'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    width: 80,
                                    dataIndex: 'proName',
                                    text: '填报年份'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'proCost',
                                    text: '开发区名称'
                                },
                                {
                                    xtype: 'actioncolumn',
                                    handler: function(view, rowIndex, colIndex, item, e, record, row) {
                                        if (colIndex === undefined || colIndex < 2) {
                                            return;
                                        }
                                        if(record.get('ismap')===1){
                                            var filepath=record.get('filePath');
                                            var index=filepath.lastIndexOf('/');
                                            if(index<=0){
                                                Ext.Msg.alert('提示','解析文件路径出错');
                                            }else{
                                                var filename=filepath.substring(index+1);
                                                filepath=filepath.substr(0,index)+'/';
                                                var nwin = window.open();
                                                var href="public/mapUpload/shppreview.html?filepath="+filepath+"&filename="+filename;
                                                nwin.location=href;
                                            }
                                        }else Ext.Msg.alert('提示','未上传图形数据');
                                    },
                                    align: 'center',
                                    dataIndex: 'proCost',
                                    text: '查看图斑',
                                    icon: 'images/table/preview1.png'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'proZhuguan',
                                    text: '开发区评价范围'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'proHezuo',
                                    text: '开发区评价类型'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'proStartTime',
                                    text: '图斑编号'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'proEndTime',
                                    text: '地类名称'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'proTeam',
                                    text: '地类面积'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'proApplication',
                                    text: '权属'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'proCheck',
                                    text: '供应时间'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'proStatus',
                                    text: '供应类型'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'tdzpg',
                                    text: '土地招拍佳情况'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'synx',
                                    text: '使用年限'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'tdsyz',
                                    text: '土地使用者'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'jzmj',
                                    text: '建筑面积(平方米)'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'jzjdmj',
                                    text: '建筑基地面积(平方米)'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'jdzmj',
                                    text: '建筑物、构筑物基底及露天堆场、露天操作场地的总面积（平方米）'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'gxlb',
                                    text: '高新技术产业用地类别'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'gxydmj',
                                    text: '高新技术产业用地面积(公顷）'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'gxzsbl',
                                    text: '高新技术产业用地面积折算比例 '
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'gxsr',
                                    text: '高新技术产业收入（万元）'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'gxss',
                                    text: '高新技术产业税收（万元）'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'ghyt',
                                    text: '规划用途'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'pzyt',
                                    text: '批准用途'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'proBz',
                                    text: '土地闲置情况'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'rdyj',
                                    text: '认定依据'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'gdzctzze',
                                    text: '工业企业、工业物流企业固定资产投资总额(万元）'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'esssze',
                                    text: '二、三产业税收总额（万元/年）'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'qyzsr',
                                    text: '工业企业工业物流企业总收入（万元/年）'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'check',
                                    text: '工业企业工业物流企业税收总额（万元/年）'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'bz',
                                    text: '备注'
                                }
                            ],
                            selModel: {
                                selType: 'checkboxmodel'
                            }
                        }
                    ],
                    listeners: {
                        activate: 'onPanelActivate1'
                    }
                },
                {
                    xtype: 'panel',
                    layout: 'border',
                    title: '审核未通过',
                    items: [
                        {
                            xtype: 'gridpanel',
                            region: 'center',
                            id: 'zdxx_unpass',
                            title: '',
                            sortableColumns: false,
                            store: 'costInfoStore',
                            columns: [
                                {
                                    xtype: 'rownumberer',
                                    width: 66,
                                    dataIndex: 'zdId',
                                    text: '序号'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    width: 80,
                                    dataIndex: 'proName',
                                    text: '填报年份'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'proCost',
                                    text: '开发区名称'
                                },
                                {
                                    xtype: 'actioncolumn',
                                    handler: function(view, rowIndex, colIndex, item, e, record, row) {
                                        if (colIndex === undefined || colIndex < 2) {
                                            return;
                                        }
                                        if(record.get('ismap')===1){
                                            var filepath=record.get('filePath');
                                            var index=filepath.lastIndexOf('/');
                                            if(index<=0){
                                                Ext.Msg.alert('提示','解析文件路径出错');
                                            }else{
                                                var filename=filepath.substring(index+1);
                                                filepath=filepath.substr(0,index)+'/';
                                                var nwin = window.open();
                                                var href="public/mapUpload/shppreview.html?filepath="+filepath+"&filename="+filename;
                                                nwin.location=href;
                                            }
                                        }else Ext.Msg.alert('提示','未上传图形数据');
                                    },
                                    align: 'center',
                                    dataIndex: 'proCost',
                                    text: '查看图斑',
                                    icon: 'images/table/preview1.png'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'proZhuguan',
                                    text: '开发区评价范围'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'proHezuo',
                                    text: '开发区评价类型'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'proStartTime',
                                    text: '图斑编号'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'proEndTime',
                                    text: '地类名称'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'proTeam',
                                    text: '地类面积'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'proApplication',
                                    text: '权属'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'proCheck',
                                    text: '供应时间'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'proStatus',
                                    text: '供应类型'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'tdzpg',
                                    text: '土地招拍佳情况'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'synx',
                                    text: '使用年限'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'tdsyz',
                                    text: '土地使用者'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'jzmj',
                                    text: '建筑面积(平方米)'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'jzjdmj',
                                    text: '建筑基地面积(平方米)'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'jdzmj',
                                    text: '建筑物、构筑物基底及露天堆场、露天操作场地的总面积（平方米）'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'gxlb',
                                    text: '高新技术产业用地类别'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'gxydmj',
                                    text: '高新技术产业用地面积(公顷）'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'gxzsbl',
                                    text: '高新技术产业用地面积折算比例 '
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'gxsr',
                                    text: '高新技术产业收入（万元）'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'gxss',
                                    text: '高新技术产业税收（万元）'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'ghyt',
                                    text: '规划用途'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'pzyt',
                                    text: '批准用途'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'proBz',
                                    text: '土地闲置情况'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'rdyj',
                                    text: '认定依据'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'gdzctzze',
                                    text: '工业企业、工业物流企业固定资产投资总额(万元）'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'esssze',
                                    text: '二、三产业税收总额（万元/年）'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'qyzsr',
                                    text: '工业企业工业物流企业总收入（万元/年）'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'check',
                                    text: '工业企业工业物流企业税收总额（万元/年）'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'bz',
                                    text: '备注'
                                }
                            ],
                            selModel: {
                                selType: 'checkboxmodel'
                            }
                        }
                    ],
                    listeners: {
                        activate: 'onPanelActivate2'
                    }
                }
            ]
        }
    ],
    dockedItems: [
        {
            xtype: 'toolbar',
            dock: 'top',
            items: [
                {
                    xtype: 'combobox',
                    id: 'ent_check_gradeCombo',
                    width: 181,
                    fieldLabel: '开发区级别',
                    labelWidth: 80,
                    store: 'kfqInfoStore',
                    valueField: 'mapUrl',
                    listeners: {
                        change: 'onEnt_check_gradeComboChange'
                    }
                },
                {
                    xtype: 'combobox',
                    id: 'ent_check_typeCombo',
                    width: 190,
                    fieldLabel: '开发区类型',
                    labelWidth: 80,
                    store: 'costInfoStore',
                    valueField: 'mapUrl',
                    listeners: {
                        change: 'onEnt_check_typeComboChange'
                    }
                },
                {
                    xtype: 'combobox',
                    id: 'ent_landusePropertyCheck_Combo',
                    width: 220,
                    fieldLabel: '选择开发区',
                    labelWidth: 80,
                    displayField: 'mapName',
                    store: 'costInfoStore',
                    valueField: 'mapUrl',
                    listeners: {
                        change: 'onEnt_landusePropertyCheck_ComboChange'
                    }
                },
                {
                    xtype: 'combobox',
                    id: 'ent_check_yearCombo',
                    width: 190,
                    fieldLabel: '选择年份',
                    labelWidth: 80,
                    store: 'costInfoStore',
                    valueField: 'mapUrl',
                    listeners: {
                        change: 'onEnt_check_yearComboChange'
                    }
                }
            ]
        }
    ],

    onPanelActivate: function(component, eOpts) {
        //var getKeyword = Ext.getCmp('searchKeyword_zdInfo').getValue();
        //console.log("keyword:",getKeyword);
        var mystore = Ext.StoreMgr.get('zd_checkStore'); //获得store对象
        //在load事件中添加参数
        mystore.load(
            {
                params :
                {
                    searchKeyword :0
                }
            }
        );


    },

    onPanelActivate1: function(component, eOpts) {
        var mystore = Ext.StoreMgr.get('zd_checkStore'); //获得store对象
        //在load事件中添加参数
        mystore.load(
            {
                params :
                {
                    searchKeyword : 1
                }
            }
        );
    },

    onPanelActivate2: function(component, eOpts) {
        var mystore = Ext.StoreMgr.get('zd_checkStore'); //获得store对象
        //在load事件中添加参数
        mystore.load(
            {
                params :
                {
                    searchKeyword : 2
                }
            }
        );
    },

    onEnt_check_gradeComboChange: function(field, newValue, oldValue, eOpts) {
        var getKeyword = Ext.getCmp('ent_check_gradeCombo').getValue();
        console.log("keyword:",getKeyword);
        var mystore = Ext.StoreMgr.get('zd_checkStore'); //获得store对象
        //在load事件中添加参数
        var kfqpjlx=Ext.getCmp('kfqpjlx').getValue();
        var kfqmc=Ext.getCmp('kfqmc').getValue();
        var tbnf = Ext.getCmp('tbnf').getValue();
        console.log(newValue);
        //在load事件中添加参数
        mystore.load(
        {
         params :
            {
                kfqjb:newValue,
                kfqpjlx:kfqpjlx,
                kfqmc:kfqmc,
                tbnf:tbnf

            }
        }

        );


    },

    onEnt_check_typeComboChange: function(field, newValue, oldValue, eOpts) {
        var getKeyword = Ext.getCmp('ent_check_typeCombo').getValue();
        console.log("keyword:",getKeyword);
        var mystore = Ext.StoreMgr.get('zd_checkStore'); //获得store对象
        //在load事件中添加参数
        //var kfqpjlx=Ext.getCmp('kfqpjlx').getValue();
        var kfqmc=Ext.getCmp('kfqmc').getValue();
        var tbnf = Ext.getCmp('tbnf').getValue();
        var kfqjb = Ext.getCmp('kfqjb').getValue();
        console.log(newValue);
        //在load事件中添加参数
        mystore.load(
        {
         params :
            {
                kfqjb:kfqjb,
                kfqpjlx:newValue,
                kfqmc:kfqmc,
                tbnf:tbnf

            }
        }

        );

    },

    onEnt_landusePropertyCheck_ComboChange: function(field, newValue, oldValue, eOpts) {
        var getKeyword = Ext.getCmp('ent_landusePropertyCheck_Combo').getValue();
        console.log("keyword:",getKeyword);
        var mystore = Ext.StoreMgr.get('zd_checkStore'); //获得store对象
        //在load事件中添加参数
        var kfqpjlx=Ext.getCmp('kfqpjlx').getValue();
        //var kfqmc=Ext.getCmp('kfqmc').getValue();
        var tbnf = Ext.getCmp('tbnf').getValue();
        var kfqjb = Ext.getCmp('kfqjb').getValue();
        console.log(newValue);
        //在load事件中添加参数
        mystore.load(
        {
         params :
            {
                kfqjb:kfqjb,
                kfqpjlx:kfqpjlx,
                kfqmc:newValue,
                tbnf:tbnf

            }
        }

        );

    },

    onEnt_check_yearComboChange: function(field, newValue, oldValue, eOpts) {
        var getKeyword = Ext.getCmp('ent_check_yearCombo').getValue();
        console.log("keyword:",getKeyword);
        var mystore = Ext.StoreMgr.get('zd_checkStore'); //获得store对象
        //在load事件中添加参数
        var kfqpjlx=Ext.getCmp('kfqpjlx').getValue();
        var kfqmc=Ext.getCmp('kfqmc').getValue();
        //var tbnf = Ext.getCmp('tbnf').getValue();
        var kfqjb = Ext.getCmp('kfqjb').getValue();
        console.log(newValue);
        //在load事件中添加参数
        mystore.load(
        {
         params :
            {
                kfqjb:kfqjb,
                kfqpjlx:kfqpjlx,
                kfqmc:kfqmc,
                tbnf:newValue

            }
        }

        );

    }

});