/*
 * File: app/view/kfq_add.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.kfq_add', {
    extend: 'Ext.window.Window',
    alias: 'widget.kfq_add',

    requires: [
        'MyApp.view.kfq_addViewModel',
        'Ext.form.Panel',
        'Ext.form.FieldSet',
        'Ext.form.field.ComboBox',
        'Ext.form.field.Number',
        'Ext.form.field.Date',
        'Ext.toolbar.Toolbar',
        'Ext.toolbar.Fill',
        'Ext.button.Button',
        'Ext.toolbar.Spacer'
    ],

    viewModel: {
        type: 'kfq_add'
    },
    autoScroll: true,
    height: 575,
    id: 'kfq_add',
    width: 427,
    title: '新增开发区信息表单',
    titleAlign: 'center',

    items: [
        {
            xtype: 'form',
            height: 1183,
            id: 'form_kfqinfo_add',
            width: 405,
            layout: 'absolute',
            bodyPadding: 10,
            title: '',
            jsonSubmit: false,
            url: 'add_kfqInfo',
            items: [
                {
                    xtype: 'fieldset',
                    x: 20,
                    y: 20,
                    height: 360,
                    width: 361,
                    layout: 'auto',
                    title: '开发区基本信息',
                    items: [
                        {
                            xtype: 'textfield',
                            width: 325,
                            fieldLabel: '开发区名称',
                            labelAlign: 'right',
                            labelWidth: 150,
                            name: 'kfqmc',
                            allowBlank: false
                        },
                        {
                            xtype: 'combobox',
                            width: 325,
                            fieldLabel: '开发区级别',
                            labelAlign: 'right',
                            labelWidth: 150,
                            name: 'kfqjb',
                            editable: false,
                            store: [
                                '国家级',
                                '省级',
                                '示范基地'
                            ]
                        },
                        {
                            xtype: 'textfield',
                            height: 25,
                            width: 325,
                            fieldLabel: '开发区审批单位',
                            labelAlign: 'right',
                            labelWidth: 150,
                            name: 'spdw'
                        },
                        {
                            xtype: 'textfield',
                            height: 25,
                            width: 325,
                            fieldLabel: '开发区管理机构',
                            labelAlign: 'right',
                            labelWidth: 150,
                            name: 'gljg'
                        },
                        {
                            xtype: 'textfield',
                            height: 25,
                            width: 325,
                            fieldLabel: '开发区管理机构地址',
                            labelAlign: 'right',
                            labelWidth: 150,
                            name: 'gljgdz'
                        },
                        {
                            xtype: 'textfield',
                            height: 25,
                            width: 325,
                            fieldLabel: '开发区主导产业',
                            labelAlign: 'right',
                            labelWidth: 150,
                            name: 'zdcy'
                        },
                        {
                            xtype: 'numberfield',
                            fieldLabel: '开发区依法审批土地总面积（hm2）',
                            labelAlign: 'right',
                            labelWidth: 150,
                            name: 'sptdzmj',
                            allowBlank: false,
                            blankText: '0.00',
                            hideTrigger: true
                        },
                        {
                            xtype: 'combobox',
                            height: 25,
                            width: 325,
                            fieldLabel: '开发区审批类型',
                            labelAlign: 'right',
                            labelWidth: 150,
                            name: 'kfqsplx',
                            editable: false,
                            displayField: 'name',
                            store: 'landKfqSpTypeComboStore',
                            valueField: 'value'
                        },
                        {
                            xtype: 'datefield',
                            height: 25,
                            width: 325,
                            fieldLabel: '开发区设立时间',
                            labelAlign: 'right',
                            labelWidth: 150,
                            name: 'slsj',
                            format: 'Ym'
                        },
                        {
                            xtype: 'combobox',
                            height: 25,
                            width: 325,
                            fieldLabel: '开发区评价范围',
                            labelAlign: 'right',
                            labelWidth: 150,
                            name: 'kfqpjfw',
                            allowBlank: false,
                            store: [
                                '主区',
                                '发展区'
                            ]
                        },
                        {
                            xtype: 'combobox',
                            height: 25,
                            weight: 325,
                            fieldLabel: '开发区评价类型',
                            labelAlign: 'right',
                            labelWidth: 150,
                            name: 'kfqpjlx',
                            allowBlank: false,
                            store: [
                                '产城融合型',
                                '工业主导型'
                            ]
                        }
                    ]
                },
                {
                    xtype: 'fieldset',
                    x: 20,
                    y: 390,
                    height: 376,
                    width: 360,
                    layout: 'auto',
                    title: '主区',
                    items: [
                        {
                            xtype: 'numberfield',
                            fieldLabel: '开发区评价面积（hm2）',
                            labelAlign: 'right',
                            labelWidth: 150,
                            name: 'mkfqpjmj'
                        },
                        {
                            xtype: 'numberfield',
                            fieldLabel: '土地开发率(%)',
                            labelAlign: 'right',
                            labelWidth: 150,
                            name: 'mtdkfl'
                        },
                        {
                            xtype: 'numberfield',
                            fieldLabel: '常住人口(人)',
                            labelAlign: 'right',
                            labelWidth: 150,
                            name: 'mczrk'
                        },
                        {
                            xtype: 'numberfield',
                            fieldLabel: '工业（物流）企业固定资产投资总额（万元）',
                            labelWidth: 150,
                            name: 'mgdzctzze'
                        },
                        {
                            xtype: 'numberfield',
                            fieldLabel: '二、三产业税收总额(万元)',
                            labelWidth: 150,
                            name: 'mescyssze',
                            hideTrigger: true
                        },
                        {
                            xtype: 'numberfield',
                            fieldLabel: '开发区工业（物流）企业总收入（万元）',
                            labelWidth: 150,
                            name: 'mgyzsr',
                            hideTrigger: true
                        },
                        {
                            xtype: 'numberfield',
                            fieldLabel: '开发区工业（物流）企业税收总额（万元）',
                            labelWidth: 150,
                            name: 'mgyssze',
                            hideTrigger: true
                        },
                        {
                            xtype: 'numberfield',
                            fieldLabel: '开发区高新技术产业总收入（万元）',
                            labelWidth: 150,
                            name: 'mgxzsr',
                            hideTrigger: true
                        },
                        {
                            xtype: 'numberfield',
                            fieldLabel: '开发区高新技术产业税收总额（万元）',
                            labelWidth: 150,
                            name: 'mgxssze',
                            hideTrigger: true
                        }
                    ]
                },
                {
                    xtype: 'fieldset',
                    x: 20,
                    y: 780,
                    height: 376,
                    width: 360,
                    layout: 'auto',
                    title: '发展方向区',
                    items: [
                        {
                            xtype: 'numberfield',
                            fieldLabel: '开发区评价面积（hm2）',
                            labelWidth: 150,
                            name: 'dkfqpjmj',
                            hideTrigger: true
                        },
                        {
                            xtype: 'numberfield',
                            fieldLabel: '土地开发率(%)',
                            labelWidth: 150,
                            name: 'dtdkfl',
                            hideTrigger: true
                        },
                        {
                            xtype: 'numberfield',
                            fieldLabel: '常住人口(人)',
                            labelWidth: 150,
                            name: 'dczrk',
                            hideTrigger: true
                        },
                        {
                            xtype: 'numberfield',
                            fieldLabel: '工业（物流）企业固定资产投资总额（万元）',
                            labelWidth: 150,
                            name: 'dgdzctzze',
                            hideTrigger: true
                        },
                        {
                            xtype: 'numberfield',
                            fieldLabel: '二、三产业税收总额(万元)',
                            labelAlign: 'right',
                            labelWidth: 150,
                            name: 'descyssze',
                            hideTrigger: true
                        },
                        {
                            xtype: 'numberfield',
                            fieldLabel: '开发区工业（物流）企业总收入（万元）',
                            labelWidth: 150,
                            name: 'dgyzsr',
                            hideTrigger: true
                        },
                        {
                            xtype: 'numberfield',
                            fieldLabel: '开发区工业（物流）企业税收总额（万元）',
                            labelWidth: 150,
                            name: 'dgyssze',
                            hideTrigger: true
                        },
                        {
                            xtype: 'numberfield',
                            fieldLabel: '开发区高新技术产业总收入（万元）',
                            labelWidth: 150,
                            name: 'dgxzsr',
                            hideTrigger: true
                        },
                        {
                            xtype: 'numberfield',
                            fieldLabel: '开发区高新技术产业税收总额（万元）',
                            labelWidth: 150,
                            name: 'dgxssze',
                            hideTrigger: true
                        }
                    ]
                }
            ]
        }
    ],
    dockedItems: [
        {
            xtype: 'toolbar',
            dock: 'bottom',
            height: 38,
            items: [
                {
                    xtype: 'tbfill'
                },
                {
                    xtype: 'button',
                    handler: function() {
                        Ext.getCmp('kfq_add').close();
                    },
                    text: '关闭'
                },
                {
                    xtype: 'tbspacer',
                    width: 20
                },
                {
                    xtype: 'button',
                    handler: function() {
                        //添加开发区信息,url:add_kfqinfo

                        var myform = Ext.getCmp('form_kfqinfo_add').getForm();
                        if (myform.isValid())
                        {
                            console.log('form is ava');
                            myform.submit({
                                //url : 'add_kfqinfo',
                                success : function (form, action)
                                {
                                    Ext.Msg.alert('成功', '内容添加成功。');
                                    var mystore = Ext.StoreMgr.get('kfqInfoStore'); //获得store对象
                                    mystore.reload();

                                    var win = Ext.getCmp('kfq_add');
                                    win.close();

                                },
                                failure: function(form, action){
                                    Ext.Msg.alert('失败', '内容添加失败，请重试。');
                                }
                            });
                        }
                        else
                        {
                            Ext.Msg.alert('注意', '填写的信息有误，请检查！');
                        }
                    },
                    id: 'button_add',
                    text: '增  添'
                },
                {
                    xtype: 'tbspacer',
                    width: 20
                }
            ]
        }
    ]

});