/*
 * File: app/view/MyPanel22.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.MyPanel22', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.mypanel22',

    requires: [
        'MyApp.view.MyPanel22ViewModel',
        'Ext.tab.Panel',
        'Ext.tab.Tab',
        'Ext.grid.Panel',
        'Ext.grid.column.RowNumberer',
        'Ext.grid.column.Action',
        'Ext.toolbar.Paging',
        'Ext.grid.View',
        'Ext.selection.CheckboxModel',
        'Ext.form.field.ComboBox',
        'Ext.toolbar.Fill'
    ],

    viewModel: {
        type: 'mypanel22'
    },
    height: 450,
    width: 808,
    layout: 'border',
    title: '财务报销管理',
    defaultListenerScope: true,

    items: [
        {
            xtype: 'tabpanel',
            region: 'center',
            id: 'zdxx_tab',
            activeTab: 0,
            items: [
                {
                    xtype: 'panel',
                    layout: 'border',
                    title: '未提交报销单',
                    items: [
                        {
                            xtype: 'gridpanel',
                            region: 'center',
                            autoScroll: true,
                            id: 'zd_info',
                            title: '',
                            sortableColumns: false,
                            store: 'projectInfoStore',
                            columns: [
                                {
                                    xtype: 'rownumberer',
                                    width: 66,
                                    dataIndex: 'zdId',
                                    text: '序号'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    hidden: true,
                                    width: 80,
                                    dataIndex: 'proName',
                                    text: '填报年份'
                                },
                                {
                                    xtype: 'actioncolumn',
                                    handler: function(view, rowIndex, colIndex, item, e, record, row) {
                                        if (colIndex === undefined || colIndex < 2) {
                                            return;
                                        }

                                        var tbbh=record.get('tbbh');
                                        var id=record.get('id');
                                        var tbrq=record.get('tbrq');
                                        var bgsqr=record.get('bgsqr');
                                        var kfqdm=record.get('kfqdm');
                                        var kfqmc=record.get('kfqmc');
                                        var params="tbbh="+tbbh+"&id="+id+"&tbrq="+tbrq+"&bgsqr="+bgsqr+"&kfqdm="+kfqdm+"&kfqmc="+kfqmc;
                                        if(record.get('ismap')===1){
                                            var filepath=record.get('filePath');
                                            var index=filepath.lastIndexOf('/');
                                            if(index<=0){
                                                Ext.Msg.alert('提示','解析文件路径出错');
                                                params+='&pre=false';
                                            }else{
                                                var filename=filepath.substring(index+1);
                                                filepath=filepath.substr(0,index)+'/';
                                                params+="&filepath="+filepath+"&filename="+filename+"&pre=true";
                                            }
                                        }else params+='&pre=false';

                                        var win = Ext.widget('dxqy_mapupload');

                                        win.html="<iframe src='public/mapUpload/zdbg_mapupload.html?"+params+"'scrolling='yes' frameborder=0 width=100% height=100%></iframe>";
                                        win.show();
                                    },
                                    width: 80,
                                    align: 'center',
                                    dataIndex: 'proName',
                                    text: '实时调整',
                                    icon: 'images/table/update.jpg'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'proCost',
                                    text: '开发区名称'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'proZhuguan',
                                    text: '开发区评价范围'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'proHezuo',
                                    text: '开发区评价类型'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'proStartTime',
                                    text: '图斑编号'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'proEndTime',
                                    text: '地类名称'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'proManager',
                                    text: '地类代码'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'proTeam',
                                    text: '地类面积'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'proApplication',
                                    text: '权属'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'proCheck',
                                    text: '供应时间'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'proStatus',
                                    text: '供应类型'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'tdzpg',
                                    text: '土地招拍佳情况'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'synx',
                                    text: '使用年限'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'tdsyz',
                                    text: '土地使用者'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'jzmj',
                                    text: '建筑面积(平方米)'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'jzjdmj',
                                    text: '建筑基地面积(平方米)'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'jdzmj',
                                    text: '建筑物、构筑物基底及露天堆场、露天操作场地的总面积（平方米）'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'gxlb',
                                    text: '高新技术产业用地类别'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'gxydmj',
                                    text: '高新技术产业用地面积(公顷）'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'gxzsbl',
                                    text: '高新技术产业用地面积折算比例 '
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'gxsr',
                                    text: '高新技术产业收入（万元）'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'gxss',
                                    text: '高新技术产业税收（万元）'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'ghyt',
                                    text: '规划用途'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'pzyt',
                                    text: '批准用途'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'proBz',
                                    text: '土地闲置情况'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'rdyj',
                                    text: '认定依据'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'gdzctzze',
                                    text: '工业企业、工业物流企业固定资产投资总额(万元）'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'esssze',
                                    text: '二、三产业税收总额（万元/年）'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'qyzsr',
                                    text: '工业企业工业物流企业总收入（万元/年）'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'shzt',
                                    text: '工业企业工业物流企业税收总额（万元/年）'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'bz',
                                    text: '备注'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    hidden: true,
                                    id: 'jzzk',
                                    dataIndex: 'jzzk',
                                    text: '建设状况'
                                }
                            ],
                            dockedItems: [
                                {
                                    xtype: 'pagingtoolbar',
                                    dock: 'bottom',
                                    hidden: true,
                                    width: 360,
                                    displayInfo: true,
                                    emptyMsg: '无数据',
                                    store: 'projectInfoStore'
                                },
                                {
                                    xtype: 'toolbar',
                                    dock: 'top',
                                    items: [
                                        {
                                            xtype: 'combobox',
                                            id: 'kfqmc1',
                                            width: 300,
                                            fieldLabel: '开发区名称',
                                            labelWidth: 80,
                                            displayField: 'kfqmc',
                                            store: 'kfqInfoStore',
                                            valueField: 'kfqmc',
                                            listeners: {
                                                change: 'onEnt_landuse_typeCombo1Change1'
                                            }
                                        },
                                        {
                                            xtype: 'textfield',
                                            id: 'searchKeyword_zdInfo',
                                            fieldLabel: '',
                                            emptyText: '输入搜索关键字',
                                            listeners: {
                                                change: 'onSearchKeyword_zdInfoChange'
                                            }
                                        },
                                        {
                                            xtype: 'button',
                                            handler: function(button, e) {
                                                Ext.getCmp('searchKeyword_zdInfo').setValue('');
                                                var mystore = Ext.StoreMgr.get('zd_infoStore'); //获得store对象
                                                mystore.load ({
                                                    params: {
                                                        // specify params for the first page load if using paging
                                                        start: 0,
                                                        limit: 1000,
                                                        // other params
                                                        searchKeyword: '',
                                                        isPass:3
                                                    }
                                                });
                                            },
                                            icon: 'images/table/refresh.png',
                                            text: '刷新'
                                        },
                                        {
                                            xtype: 'button',
                                            handler: function(button, e) {
                                                //获取数据
                                                var kfqmc = Ext.getCmp('kfqmc1').getValue();
                                                console.log("kfqmc:",kfqmc);
                                                if ( kfqmc === null){
                                                    Ext.Msg.alert('提示', '请选择开发区名称！');
                                                    return;
                                                } else {
                                                    //Ext.Msg.alert('提示', '每次只能修改一条信息，请重新选择。');
                                                    var win = Ext.widget('zdxx_add');
                                                    console.log(win);
                                                    win.show();

                                                    var mystore = Ext.StoreMgr.get('kfqInfoStore'); //获得store对象
                                                    var record =mystore.findRecord("kfqmc",kfqmc);
                                                    console.log("record2:",record);
                                                    mystore.reload();

                                                    //var models = Ext.getCmp('kfqInfo_grid').getSelection();
                                                    var form1 = Ext.getCmp('add_zdwidinfo1').getForm();
                                                    form1.loadRecord(record);
                                                    var form2 = Ext.getCmp('add_zdwidinfo2').getForm();
                                                    form2.loadRecord(record);
                                                    var form3 = Ext.getCmp('add_zdwidinfo3').getForm();
                                                    form3.loadRecord(record);



                                                    return;
                                                }
                                            },
                                            icon: 'images/table/add.png',
                                            text: '添加'
                                        },
                                        {
                                            xtype: 'button',
                                            handler: function(button, e) {
                                                //获取数据
                                                var models = Ext.getCmp('zd_info').getSelection();
                                                if (models.length === 0){
                                                    Ext.Msg.alert('提示', '请选择一条数据后再修改信息。');
                                                    return;
                                                } else if(models.length >1){
                                                    Ext.Msg.alert('提示', '每次只能修改一条信息，请重新选择。');
                                                    return;
                                                }
                                                //启动窗口
                                                var win = Ext.widget('zdxx_add');
                                                win.setTitle('修改宗地信息');
                                                win.show();

                                                var grid = Ext.getCmp('zd_info');
                                                var records = grid.getSelection();
                                                console.log("record:",records);
                                                var kfqmc =records[0].get("kfqmc");
                                                //var jszk = record.get('jzzk');
                                                console.log("kfqmc:",kfqmc);
                                                var mystore = Ext.StoreMgr.get('kfqInfoStore'); //获得store对象
                                                var record =mystore.findRecord("kfqmc",kfqmc);
                                                console.log("record2:",record);
                                                mystore.reload();

                                                //var models = Ext.getCmp('kfqInfo_grid').getSelection();
                                                var form1 = Ext.getCmp('add_zdwidinfo1').getForm();
                                                form1.loadRecord(record);
                                                var form2 = Ext.getCmp('add_zdwidinfo2').getForm();
                                                form2.loadRecord(record);
                                                var form3 = Ext.getCmp('add_zdwidinfo3').getForm();
                                                form3.loadRecord(record);

                                                //改变Ajax url
                                                // var jzzk = Ext.getCmp('jzzk').getValue();
                                                var grid = Ext.getCmp('zd_info');
                                                var records = grid.getSelection();
                                                console.log("record:",records);
                                                var jszk =records[0].get("jzzk");
                                                //var jszk = record.get('jzzk');
                                                console.log("jszk:",jszk);
                                                if(jszk=="已建成建设用地"){
                                                    console.log("jszk:",jszk);
                                                    var tab = Ext.getCmp('zdinformation');
                                                    tab.setActiveTab('title1');
                                                    var form1 = Ext.getCmp('add_zdwidinfo1').getForm();
                                                    form1.loadRecord(models[0]);
                                                    form1.url = 'update_zdInfo';


                                                    //     var tab2 = Ext.getCmp('title2');
                                                    //     tab2.setHidden(true);
                                                    //     console.log("table:",tab2);
                                                    //     var tab3 = Ext.getCmp('title3');
                                                    //     tab3.setHidden(true);

                                                }else
                                                if(jszk=="未建成建设用地"){
                                                    var tab = Ext.getCmp('zdinformation');
                                                    tab.setActiveTab('title2');
                                                    var form2 = Ext.getCmp('add_zdwidinfo2').getForm();
                                                    form2.loadRecord(models[0]);
                                                    form2.url = 'update_zdInfo';

                                                    //     var tab1 = Ext.getCmp('title1');
                                                    //     tab1.setHidden(true);
                                                    //     var tab3 = Ext.getCmp('title3');
                                                    //     tab3.setHidden(true);
                                                }else
                                                {
                                                    var tab = Ext.getCmp('zdinformation');
                                                    tab.setActiveTab('title3');
                                                    var form3 = Ext.getCmp('add_zdwidinfo3').getForm();
                                                    form3.loadRecord(models[0]);
                                                    form3.url = 'update_zdInfo';
                                                    //     var tab2 = Ext.getCmp('title2');
                                                    //     tab2.setHidden(true);
                                                    //     var tab1 = Ext.getCmp('title1');
                                                    //     tab1.setHidden(true);
                                                }

                                            },
                                            icon: 'images/table/edit.png',
                                            text: '编辑'
                                        }
                                    ]
                                }
                            ],
                            selModel: {
                                selType: 'checkboxmodel'
                            }
                        }
                    ],
                    listeners: {
                        activate: 'onPanelActivate'
                    }
                },
                {
                    xtype: 'panel',
                    id: 'committitle',
                    title: '已提交报销单',
                    items: [
                        {
                            xtype: 'gridpanel',
                            autoScroll: true,
                            id: 'zd_info1',
                            title: '',
                            sortableColumns: false,
                            store: 'projectInfoStore',
                            columns: [
                                {
                                    xtype: 'rownumberer',
                                    width: 66,
                                    dataIndex: 'zdId',
                                    text: '序号'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    width: 80,
                                    dataIndex: 'proName',
                                    text: '填报年份'
                                },
                                {
                                    xtype: 'actioncolumn',
                                    handler: function(view, rowIndex, colIndex, item, e, record, row) {
                                        if (colIndex === undefined || colIndex < 2) {
                                            return;
                                        }
                                        if(record.get('ismap')===1){
                                            var filepath=record.get('filePath');
                                            var index=filepath.lastIndexOf('/');
                                            if(index<=0){
                                                Ext.Msg.alert('提示','解析文件路径出错');
                                            }else{
                                                var filename=filepath.substring(index+1);
                                                filepath=filepath.substr(0,index)+'/';
                                                var nwin = window.open();
                                                var href="public/mapUpload/shppreview.html?filepath="+filepath+"&filename="+filename;
                                                nwin.location=href;
                                            }
                                        }else Ext.Msg.alert('提示','未上传图形数据');
                                    },
                                    width: 80,
                                    dataIndex: 'proName',
                                    text: '实时调整',
                                    icon: 'images/table/update.jpg'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'proCost',
                                    text: '开发区名称'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'proZhuguan',
                                    text: '开发区评价范围'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'proHezuo',
                                    text: '开发区评价类型'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'proStartTime',
                                    text: '图斑编号'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'proEndTime',
                                    text: '地类名称'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'proTeam',
                                    text: '地类面积'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'proApplication',
                                    text: '权属'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'proCheck',
                                    text: '供应时间'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'proStatus',
                                    text: '供应类型'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'tdzpg',
                                    text: '土地招拍佳情况'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'synx',
                                    text: '使用年限'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'tdsyz',
                                    text: '土地使用者'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'jzmj',
                                    text: '建筑面积(平方米)'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'jzjdmj',
                                    text: '建筑基地面积(平方米)'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'jdzmj',
                                    text: '建筑物、构筑物基底及露天堆场、露天操作场地的总面积（平方米）'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'gxlb',
                                    text: '高新技术产业用地类别'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'gxydmj',
                                    text: '高新技术产业用地面积(公顷）'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'gxzsbl',
                                    text: '高新技术产业用地面积折算比例 '
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'gxsr',
                                    text: '高新技术产业收入（万元）'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'gxss',
                                    text: '高新技术产业税收（万元）'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'ghyt',
                                    text: '规划用途'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'pzyt',
                                    text: '批准用途'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'proBz',
                                    text: '土地闲置情况'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'rdyj',
                                    text: '认定依据'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'gdzctzze',
                                    text: '工业企业、工业物流企业固定资产投资总额(万元）'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'esssze',
                                    text: '二、三产业税收总额（万元/年）'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'qyzsr',
                                    text: '工业企业工业物流企业总收入（万元/年）'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'shzt',
                                    text: '工业企业工业物流企业税收总额（万元/年）'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'bz',
                                    text: '备注'
                                }
                            ],
                            selModel: {
                                selType: 'checkboxmodel'
                            },
                            dockedItems: [
                                {
                                    xtype: 'toolbar',
                                    dock: 'top',
                                    items: [
                                        {
                                            xtype: 'combobox',
                                            id: 'kfqmc3',
                                            width: 250,
                                            fieldLabel: '开发区名称',
                                            labelWidth: 80,
                                            displayField: 'kfqmc',
                                            store: 'kfqInfoStore',
                                            valueField: 'kfqmc',
                                            listeners: {
                                                change: 'onEnt_landuse_typeCombo1Change11'
                                            }
                                        },
                                        {
                                            xtype: 'textfield',
                                            id: 'searchKeyword_zdInfo1',
                                            fieldLabel: '',
                                            emptyText: '输入搜索关键字',
                                            listeners: {
                                                change: 'onSearchKeyword_zdInfoChange1'
                                            }
                                        },
                                        {
                                            xtype: 'button',
                                            handler: function(button, e) {
                                                Ext.getCmp('searchKeyword_zdInfo').setValue('');
                                                var mystore = Ext.StoreMgr.get('zd_infoStore'); //获得store对象
                                                mystore.load ({
                                                    params: {
                                                        // specify params for the first page load if using paging
                                                        start: 0,
                                                        limit: 1000,
                                                        // other params
                                                        searchKeyword: '',
                                                        isPass:4
                                                    }
                                                });
                                            },
                                            icon: 'images/table/refresh.png',
                                            text: '刷新'
                                        },
                                        {
                                            xtype: 'button',
                                            handler: function(button, e) {
                                                // var win = Ext.widget('zdxx_add');
                                                // //console.log(win);
                                                // win.show();

                                                //获取数据
                                                var kfqmc = Ext.getCmp('kfqmc3').getValue();
                                                console.log("kfqmc:",kfqmc);
                                                if ( kfqmc === null){
                                                    Ext.Msg.alert('提示', '请选择开发区名称！');
                                                    return;
                                                } else {
                                                    //Ext.Msg.alert('提示', '每次只能修改一条信息，请重新选择。');
                                                    var win = Ext.widget('zdxx_add');
                                                    console.log(win);
                                                    win.show();

                                                    var mystore = Ext.StoreMgr.get('kfqInfoStore'); //获得store对象
                                                    var record =mystore.findRecord("kfqmc",kfqmc);
                                                    console.log("record2:",record);
                                                    mystore.reload();

                                                    //var models = Ext.getCmp('kfqInfo_grid').getSelection();
                                                    var form1 = Ext.getCmp('add_zdwidinfo1').getForm();
                                                    form1.loadRecord(record);
                                                    var form2 = Ext.getCmp('add_zdwidinfo2').getForm();
                                                    form2.loadRecord(record);
                                                    var form3 = Ext.getCmp('add_zdwidinfo3').getForm();
                                                    form3.loadRecord(record);
                                                    return;
                                                }
                                            },
                                            hidden: true,
                                            icon: 'images/table/add.png',
                                            text: '添加'
                                        },
                                        {
                                            xtype: 'button',
                                            handler: function(button, e) {
                                                // //获取数据
                                                // var models = Ext.getCmp('zd_info').getSelection();
                                                // if (models.length === 0){
                                                //     Ext.Msg.alert('提示', '请选择一条数据后再修改信息。');
                                                //     return;
                                                // } else if(models.length >1){
                                                //     Ext.Msg.alert('提示', '每次只能修改一条信息，请重新选择。');
                                                //     return;
                                                // }
                                                // //启动窗口
                                                // var win = Ext.widget('zdxx_add');
                                                // win.setTitle('修改宗地信息');
                                                // win.show();

                                                // //改变Ajax url
                                                // var form = Ext.getCmp('add_zdwidinfo').getForm();
                                                // form.loadRecord(models[0]);
                                                // form.url = 'update_zdInfo';

                                                //获取数据
                                                var models = Ext.getCmp('zd_info1').getSelection();
                                                if (models.length === 0){
                                                    Ext.Msg.alert('提示', '请选择一条数据后再修改信息。');
                                                    return;
                                                } else if(models.length >1){
                                                    Ext.Msg.alert('提示', '每次只能修改一条信息，请重新选择。');
                                                    return;
                                                }
                                                //启动窗口
                                                var win = Ext.widget('zdxx_add');
                                                win.setTitle('修改宗地信息');
                                                win.show();

                                                //改变Ajax url
                                                // var jzzk = Ext.getCmp('jzzk').getValue();
                                                var grid = Ext.getCmp('zd_info1');
                                                var records = grid.getSelection();
                                                console.log("record:",records);
                                                var jszk =records[0].get("jzzk");
                                                //var jszk = record.get('jzzk');
                                                console.log("jszk:",jszk);
                                                if(jszk=="已建成建设用地"){
                                                    console.log("jszk:",jszk);
                                                    var tab = Ext.getCmp('zdinformation');
                                                    tab.setActiveTab('title1');
                                                    var form1 = Ext.getCmp('add_zdwidinfo1').getForm();
                                                    form1.loadRecord(models[0]);
                                                    form1.url = 'update_zdInfo';


                                                    //     var tab2 = Ext.getCmp('title2');
                                                    //     tab2.setHidden(true);
                                                    //     console.log("table:",tab2);
                                                    //     var tab3 = Ext.getCmp('title3');
                                                    //     tab3.setHidden(true);

                                                }else
                                                if(jszk=="未建成建设用地"){
                                                    var tab = Ext.getCmp('zdinformation');
                                                    tab.setActiveTab('title2');
                                                    var form2 = Ext.getCmp('add_zdwidinfo2').getForm();
                                                    form2.loadRecord(models[0]);
                                                    form2.url = 'update_zdInfo';

                                                    //     var tab1 = Ext.getCmp('title1');
                                                    //     tab1.setHidden(true);
                                                    //     var tab3 = Ext.getCmp('title3');
                                                    //     tab3.setHidden(true);
                                                }else
                                                {
                                                    var tab = Ext.getCmp('zdinformation');
                                                    tab.setActiveTab('title3');
                                                    var form3 = Ext.getCmp('add_zdwidinfo3').getForm();
                                                    form3.loadRecord(models[0]);
                                                    form3.url = 'update_zdInfo';
                                                    //     var tab2 = Ext.getCmp('title2');
                                                    //     tab2.setHidden(true);
                                                    //     var tab1 = Ext.getCmp('title1');
                                                    //     tab1.setHidden(true);
                                                }

                                                // // var jzzk = Ext.getCmp('jzzk');
                                                // // console.log("jzzk:",jzzk.getvalue());
                                                // var tab = Ext.getCmp('zdinformation');
                                                // var form1 = Ext.getCmp('add_zdwidinfo2').getForm();
                                                // form1.loadRecord(models[0]);
                                                // form1.url = 'update_zdInfo';
                                                // var title = Ext.getCmp('title1');
                                                // console.log(title.getTitle());
                                                // var title1 = Ext.getCmp('title2');
                                                // console.log(title1.getTitle());
                                                // var title2 = Ext.getCmp('title3');
                                                // console.log(title2.getTitle());
                                                // var tab2 = Ext.getCmp('title2');
                                                // tab2.setHidden('true');
                                                // var tab3 = Ext.getCmp('title3');
                                                // tab3.setHidden('true');

                                            },
                                            hidden: true,
                                            icon: 'images/table/edit.png',
                                            text: '编辑'
                                        }
                                    ]
                                }
                            ]
                        }
                    ],
                    listeners: {
                        activate: 'onPanelActivate1'
                    }
                },
                {
                    xtype: 'panel',
                    title: '审批驳回报销单',
                    items: [
                        {
                            xtype: 'gridpanel',
                            autoScroll: true,
                            id: 'zd_info2',
                            title: '',
                            sortableColumns: false,
                            store: 'projectInfoStore',
                            columns: [
                                {
                                    xtype: 'rownumberer',
                                    width: 66,
                                    dataIndex: 'zdId',
                                    text: '序号'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    width: 80,
                                    dataIndex: 'proName',
                                    text: '填报年份'
                                },
                                {
                                    xtype: 'actioncolumn',
                                    handler: function(view, rowIndex, colIndex, item, e, record, row) {
                                        if (colIndex === undefined || colIndex < 2) {
                                            return;
                                        }

                                        var tbbh=record.get('tbbh');
                                        var id=record.get('id');
                                        var tbrq=record.get('tbrq');
                                        var bgsqr=record.get('bgsqr');
                                        var kfqdm=record.get('kfqdm');
                                        var kfqmc=record.get('kfqmc');
                                        var params="tbbh="+tbbh+"&id="+id+"&tbrq="+tbrq+"&bgsqr="+bgsqr+"&kfqdm="+kfqdm+"&kfqmc="+kfqmc;
                                        if(record.get('ismap')===1){
                                            var filepath=record.get('filePath');
                                            var index=filepath.lastIndexOf('/');
                                            if(index<=0){
                                                Ext.Msg.alert('提示','解析文件路径出错');
                                                params+='&pre=false';
                                            }else{
                                                var filename=filepath.substring(index+1);
                                                filepath=filepath.substr(0,index)+'/';
                                                params+="&filepath="+filepath+"&filename="+filename+"&pre=true";
                                            }
                                        }else params+='&pre=false';

                                        var win = Ext.widget('dxqy_mapupload');

                                        win.html="<iframe src='public/mapUpload/zdbg_mapupload.html?"+params+"'scrolling='yes' frameborder=0 width=100% height=100%></iframe>";
                                        win.show();
                                    },
                                    width: 80,
                                    dataIndex: 'proName',
                                    text: '实时调整',
                                    icon: 'images/table/update.jpg'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'proCost',
                                    text: '开发区名称'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'proZhuguan',
                                    text: '开发区评价范围'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'proHezuo',
                                    text: '开发区评价类型'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'proStartTime',
                                    text: '图斑编号'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'proEndTime',
                                    text: '地类名称'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'proTeam',
                                    text: '地类面积'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'proApplication',
                                    text: '权属'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'proCheck',
                                    text: '供应时间'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'proStatus',
                                    text: '供应类型'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'tdzpg',
                                    text: '土地招拍佳情况'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'synx',
                                    text: '使用年限'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'tdsyz',
                                    text: '土地使用者'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'jzmj',
                                    text: '建筑面积(平方米)'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'jzjdmj',
                                    text: '建筑基地面积(平方米)'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'jdzmj',
                                    text: '建筑物、构筑物基底及露天堆场、露天操作场地的总面积（平方米）'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'gxlb',
                                    text: '高新技术产业用地类别'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'gxydmj',
                                    text: '高新技术产业用地面积(公顷）'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'gxzsbl',
                                    text: '高新技术产业用地面积折算比例 '
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'gxsr',
                                    text: '高新技术产业收入（万元）'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'gxss',
                                    text: '高新技术产业税收（万元）'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'ghyt',
                                    text: '规划用途'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'pzyt',
                                    text: '批准用途'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'proBz',
                                    text: '土地闲置情况'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'rdyj',
                                    text: '认定依据'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'gdzctzze',
                                    text: '工业企业、工业物流企业固定资产投资总额(万元）'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'esssze',
                                    text: '二、三产业税收总额（万元/年）'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'qyzsr',
                                    text: '工业企业工业物流企业总收入（万元/年）'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'shzt',
                                    text: '工业企业工业物流企业税收总额（万元/年）'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'bz',
                                    text: '备注'
                                }
                            ],
                            selModel: {
                                selType: 'checkboxmodel'
                            },
                            dockedItems: [
                                {
                                    xtype: 'toolbar',
                                    dock: 'top',
                                    items: [
                                        {
                                            xtype: 'combobox',
                                            id: 'kfqmc4',
                                            width: 250,
                                            fieldLabel: '开发区名称',
                                            labelWidth: 80,
                                            displayField: 'kfqmc',
                                            store: 'kfqInfoStore',
                                            valueField: 'kfqmc',
                                            listeners: {
                                                change: 'onEnt_landuse_typeCombo1Change111'
                                            }
                                        },
                                        {
                                            xtype: 'textfield',
                                            id: 'searchKeyword_zdInfo2',
                                            fieldLabel: '',
                                            emptyText: '输入搜索关键字',
                                            listeners: {
                                                change: 'onSearchKeyword_zdInfoChange11'
                                            }
                                        },
                                        {
                                            xtype: 'button',
                                            handler: function(button, e) {
                                                Ext.getCmp('searchKeyword_zdInfo').setValue('');
                                                //var mystore = Ext.StoreMgr.get('zd_infoStore'); //获得store对象
                                                var mystore = Ext.StoreMgr.get('zd_infoStore'); //获得store对象
                                                mystore.load ({
                                                    params: {
                                                        // specify params for the first page load if using paging
                                                        start: 0,
                                                        limit: 1000,
                                                        // other params
                                                        searchKeyword: '',
                                                        isPass:5
                                                    }
                                                });
                                            },
                                            icon: 'images/table/refresh.png',
                                            text: '刷新'
                                        },
                                        {
                                            xtype: 'button',
                                            handler: function(button, e) {
                                                // var win = Ext.widget('zdxx_add');
                                                // //console.log(win);
                                                // win.show();
                                                //获取数据
                                                var kfqmc = Ext.getCmp('kfqmc4').getValue();
                                                console.log("kfqmc:",kfqmc);
                                                if ( kfqmc === null){
                                                    Ext.Msg.alert('提示', '请选择开发区名称！');
                                                    return;
                                                } else {
                                                    //Ext.Msg.alert('提示', '每次只能修改一条信息，请重新选择。');
                                                    var win = Ext.widget('zdxx_add');
                                                    console.log(win);
                                                    win.show();

                                                    var mystore = Ext.StoreMgr.get('kfqInfoStore'); //获得store对象
                                                    var record =mystore.findRecord("kfqmc",kfqmc);
                                                    console.log("record2:",record);
                                                    mystore.reload();

                                                    //var models = Ext.getCmp('kfqInfo_grid').getSelection();
                                                    var form1 = Ext.getCmp('add_zdwidinfo1').getForm();
                                                    form1.loadRecord(record);
                                                    var form2 = Ext.getCmp('add_zdwidinfo2').getForm();
                                                    form2.loadRecord(record);
                                                    var form3 = Ext.getCmp('add_zdwidinfo3').getForm();
                                                    form3.loadRecord(record);



                                                    return;
                                                }
                                            },
                                            hidden: true,
                                            icon: 'images/table/add.png',
                                            text: '添加'
                                        },
                                        {
                                            xtype: 'button',
                                            handler: function(button, e) {
                                                // //获取数据
                                                // var models = Ext.getCmp('zd_info').getSelection();
                                                // if (models.length === 0){
                                                //     Ext.Msg.alert('提示', '请选择一条数据后再修改信息。');
                                                //     return;
                                                // } else if(models.length >1){
                                                //     Ext.Msg.alert('提示', '每次只能修改一条信息，请重新选择。');
                                                //     return;
                                                // }
                                                // //启动窗口
                                                // var win = Ext.widget('zdxx_add');
                                                // win.setTitle('修改宗地信息');
                                                // win.show();

                                                // //改变Ajax url
                                                // var form = Ext.getCmp('add_zdwidinfo').getForm();
                                                // form.loadRecord(models[0]);
                                                // form.url = 'update_zdInfo';

                                                //获取数据
                                                var models = Ext.getCmp('zd_info2').getSelection();
                                                if (models.length === 0){
                                                    Ext.Msg.alert('提示', '请选择一条数据后再修改信息。');
                                                    return;
                                                } else if(models.length >1){
                                                    Ext.Msg.alert('提示', '每次只能修改一条信息，请重新选择。');
                                                    return;
                                                }
                                                //启动窗口
                                                var win = Ext.widget('zdxx_add');
                                                win.setTitle('修改宗地信息');
                                                win.show();

                                                var grid = Ext.getCmp('zd_info2');
                                                var records = grid.getSelection();
                                                console.log("record:",records);
                                                var kfqmc =records[0].get("kfqmc");
                                                //var jszk = record.get('jzzk');
                                                console.log("kfqmc:",kfqmc);
                                                var mystore = Ext.StoreMgr.get('kfqInfoStore'); //获得store对象
                                                var record =mystore.findRecord("kfqmc",kfqmc);
                                                console.log("record2:",record);
                                                mystore.reload();

                                                //var models = Ext.getCmp('kfqInfo_grid').getSelection();
                                                var form1 = Ext.getCmp('add_zdwidinfo1').getForm();
                                                form1.loadRecord(record);
                                                var form2 = Ext.getCmp('add_zdwidinfo2').getForm();
                                                form2.loadRecord(record);
                                                var form3 = Ext.getCmp('add_zdwidinfo3').getForm();
                                                form3.loadRecord(record);

                                                //改变Ajax url
                                                // var jzzk = Ext.getCmp('jzzk').getValue();
                                                var grid = Ext.getCmp('zd_info2');
                                                var records = grid.getSelection();
                                                console.log("record:",records);
                                                var jszk =records[0].get("jzzk");
                                                //var jszk = record.get('jzzk');
                                                console.log("jszk:",jszk);
                                                if(jszk=="已建成建设用地"){
                                                    console.log("jszk:",jszk);
                                                    var tab = Ext.getCmp('zdinformation');
                                                    tab.setActiveTab('title1');
                                                    var form1 = Ext.getCmp('add_zdwidinfo1').getForm();
                                                    form1.loadRecord(models[0]);
                                                    form1.url = 'update_zdInfo';


                                                    //     var tab2 = Ext.getCmp('title2');
                                                    //     tab2.setHidden(true);
                                                    //     console.log("table:",tab2);
                                                    //     var tab3 = Ext.getCmp('title3');
                                                    //     tab3.setHidden(true);

                                                }else
                                                if(jszk=="未建成建设用地"){
                                                    var tab = Ext.getCmp('zdinformation');
                                                    tab.setActiveTab('title2');
                                                    var form2 = Ext.getCmp('add_zdwidinfo2').getForm();
                                                    form2.loadRecord(models[0]);
                                                    form2.url = 'update_zdInfo';

                                                    //     var tab1 = Ext.getCmp('title1');
                                                    //     tab1.setHidden(true);
                                                    //     var tab3 = Ext.getCmp('title3');
                                                    //     tab3.setHidden(true);
                                                }else
                                                {
                                                    var tab = Ext.getCmp('zdinformation');
                                                    tab.setActiveTab('title3');
                                                    var form3 = Ext.getCmp('add_zdwidinfo3').getForm();
                                                    form3.loadRecord(models[0]);
                                                    form3.url = 'update_zdInfo';
                                                    //     var tab2 = Ext.getCmp('title2');
                                                    //     tab2.setHidden(true);
                                                    //     var tab1 = Ext.getCmp('title1');
                                                    //     tab1.setHidden(true);
                                                }

                                                // // var jzzk = Ext.getCmp('jzzk');
                                                // // console.log("jzzk:",jzzk.getvalue());
                                                // var tab = Ext.getCmp('zdinformation');
                                                // var form1 = Ext.getCmp('add_zdwidinfo2').getForm();
                                                // form1.loadRecord(models[0]);
                                                // form1.url = 'update_zdInfo';
                                                // var title = Ext.getCmp('title1');
                                                // console.log(title.getTitle());
                                                // var title1 = Ext.getCmp('title2');
                                                // console.log(title1.getTitle());
                                                // var title2 = Ext.getCmp('title3');
                                                // console.log(title2.getTitle());
                                                // var tab2 = Ext.getCmp('title2');
                                                // tab2.setHidden('true');
                                                // var tab3 = Ext.getCmp('title3');
                                                // tab3.setHidden('true');

                                            },
                                            icon: 'images/table/edit.png',
                                            text: '编辑'
                                        }
                                    ]
                                }
                            ]
                        }
                    ],
                    listeners: {
                        activate: 'onPanelActivate2'
                    }
                }
            ]
        }
    ],
    listeners: {
        afterrender: 'onPanelAfterRender'
    },
    dockedItems: [
        {
            xtype: 'toolbar',
            dock: 'bottom',
            items: [
                {
                    xtype: 'tbfill'
                },
                {
                    xtype: 'textfield',
                    id: 'zd_records',
                    fieldLabel: '记录总计：',
                    editable: false
                }
            ]
        }
    ],

    onEnt_landuse_typeCombo1Change1: function(field, newValue, oldValue, eOpts) {
        // var mystore = Ext.StoreMgr.get('zd_infoStore'); //获得store对象
        // //var kfqjb=Ext.getCmp('kfqjb').getValue();
        // //var kfqmc=Ext.getCmp('kfqmc').getValue();
        // //console.log(newValue);
        // //在load事件中添加参数
        // mystore.load(
        // {
        //  params :
        //     {
        //         //kfqjb:kfqjb,
        //         //kfqpjlx:newValue,
        //         searchKeyword:newValue


        //     }
        // }

        // );

        var getKeyword = Ext.getCmp('kfqmc1').getValue();
        console.log("keyword:",getKeyword);
        var mystore = Ext.StoreMgr.get('zd_infoStore'); //获得store对象
        //在load事件中添加参数
        mystore.load(
            {
                params :
                {
                    searchKeyword : newValue,
                    isPass : 3,
                    start:0,
                    limit:1000
                }
            }
        );

    },

    onSearchKeyword_zdInfoChange: function(field, newValue, oldValue, eOpts) {
        var getKeyword = Ext.getCmp('searchKeyword_zdInfo').getValue();
        console.log("keyword:",getKeyword);
        var mystore = Ext.StoreMgr.get('zd_infoStore'); //获得store对象
        var kfqmc = Ext.getCmp('kfqmc1').getValue();
        console.log("kfqmc:",kfqmc);
        if(kfqmc !== null){
            console.log("kfqmc1:",kfqmc);
           mystore.filter("kfqmc",kfqmc);
        }
        //在load事件中添加参数
        mystore.load(
            {
                params :
                {
                    searchKeyword : newValue,
                    isPass:3,
                    start:0,
                    limit:1000
                }
            }
        );
        var kfqmc = Ext.getCmp('kfqmc1').getValue();
        console.log("kfqmc:",kfqmc);
        if(kfqmc !== null){
            console.log("kfqmc1:",kfqmc);
           mystore.filter("kfqmc",kfqmc);
        }
        //mystore.reload();
    },

    onPanelActivate: function(component, eOpts) {
        var store=Ext.StoreMgr.get('zd_infoStore');
        store.load ({
            params: {
                // specify params for the first page load if using paging
                start: 0,
                limit: 1000,
                // other params
                searchKeyword: '',
                isPass:3
            }
        });

        // store.load({
        //    params: {
        //         // specify params for the first page load if using paging
        //         start: 0,
        //         limit: 10,
        //         // other params
        //         searchKeyword: ''
        //     },
        //     callback: function(records, operation, success) {
        //                 for(var index in records){
        //                     var isPass = records[index].get('isPass');
        //                     console.log("ispass:",isPass);
        // //                     if(isPass == 3){

        // //                     }
        //                 }
        //                 //form.loadRecord(recordIdeal);

        // //         var dldmvalue = records[0].get('dldm');
        // //         var dldm = Ext.getCmp('dldm');
        // //         dldm.setValue(dldmvalue);
        // //         console.log("dldmvalue:",dldmvalue);
        // //         console.log("dldm:",dldm);
        //     }
        // });
    },

    onEnt_landuse_typeCombo1Change11: function(field, newValue, oldValue, eOpts) {
        // var mystore = Ext.StoreMgr.get('zd_infoStore'); //获得store对象
        // //var kfqjb=Ext.getCmp('kfqjb').getValue();
        // //var kfqmc=Ext.getCmp('kfqmc').getValue();
        // //console.log(newValue);
        // //在load事件中添加参数
        // mystore.load(
        // {
        //  params :
        //     {
        //         //kfqjb:kfqjb,
        //         //kfqpjlx:newValue,
        //         searchKeyword:newValue


        //     }
        // }

        // );

        var getKeyword = Ext.getCmp('kfqmc3').getValue();
        console.log("keyword:",getKeyword);
        var mystore = Ext.StoreMgr.get('zd_infoStore'); //获得store对象
        //在load事件中添加参数
        mystore.load(
            {
                params :
                {
                    searchKeyword : newValue,
                    isPass:4,
                    start:0,
                    limit:1000
                }
            }
        );

    },

    onSearchKeyword_zdInfoChange1: function(field, newValue, oldValue, eOpts) {
        var getKeyword = Ext.getCmp('searchKeyword_zdInfo').getValue();
        console.log("keyword:",getKeyword);
        var mystore = Ext.StoreMgr.get('zd_infoStore'); //获得store对象
        //var kfqmc = Ext.GetCmp();
        var kfqmc = Ext.getCmp('kfqmc3').getValue();
        console.log("kfqmc:",kfqmc);
        if(kfqmc !== null){
            console.log("kfqmc1:",kfqmc);
           mystore.filter("kfqmc",kfqmc);
        }
        //在load事件中添加参数
        mystore.load(
            {
                params :
                {
                    searchKeyword : newValue,
                    isPass : 4,
                    start:0,
                    limit:1000
                }
            }
        );

        //mystore.reload();
    },

    onPanelActivate1: function(component, eOpts) {
        var store=Ext.StoreMgr.get('zd_infoStore');
        store.load ({
         params: {
                // specify params for the first page load if using paging
                start: 0,
                limit: 1000,
                // other params
                searchKeyword: '',
                isPass:4
            }
        });
    },

    onEnt_landuse_typeCombo1Change111: function(field, newValue, oldValue, eOpts) {
        // var mystore = Ext.StoreMgr.get('zd_infoStore'); //获得store对象
        // //var kfqjb=Ext.getCmp('kfqjb').getValue();
        // //var kfqmc=Ext.getCmp('kfqmc').getValue();
        // //console.log(newValue);
        // //在load事件中添加参数
        // mystore.load(
        // {
        //  params :
        //     {
        //         //kfqjb:kfqjb,
        //         //kfqpjlx:newValue,
        //         searchKeyword:newValue


        //     }
        // }

        // );

        var getKeyword = Ext.getCmp('kfqmc3').getValue();
        console.log("keyword:",getKeyword);
        var mystore = Ext.StoreMgr.get('zd_infoStore'); //获得store对象
        //在load事件中添加参数
        mystore.load(
            {
                params :
                {
                    searchKeyword : newValue,
                    isPass:5,
                    start:0,
                    limit:1000
                }
            }
        );

    },

    onSearchKeyword_zdInfoChange11: function(field, newValue, oldValue, eOpts) {
        var getKeyword = Ext.getCmp('searchKeyword_zdInfo').getValue();
        console.log("keyword:",getKeyword);
        var mystore = Ext.StoreMgr.get('zd_infoStore'); //获得store对象

        var kfqmc = Ext.getCmp('kfqmc4').getValue();
        console.log("kfqmc:",kfqmc);
        if(kfqmc !== null){
            console.log("kfqmc1:",kfqmc);
           mystore.filter("kfqmc",kfqmc);
        }
        //在load事件中添加参数
        mystore.load(
            {
                params :
                {
                    searchKeyword : newValue,
                    isPass:5,
                    start:0,
                    limit:1000
                }
            }
        );
    },

    onPanelActivate2: function(component, eOpts) {
        var store=Ext.StoreMgr.get('zd_infoStore');
        store.load ({
         params: {
                // specify params for the first page load if using paging
                start: 0,
                limit: 1000,
                // other params
                searchKeyword: '',
                isPass:5
            }
        });
    },

    onPanelAfterRender: function(component, eOpts) {
        var store=Ext.StoreMgr.get('zd_infoStore');
        console.log("store:",store);
        console.log(store.getCount());
        // var record = store.findRecord('dlmc',newValue);
        // console.log(record);
        // var dm = record.get('dldm');
        // console.log(dm);
        store.load(
            {
                params :
                {
                    searchKeyword : ''
                }
            }
        );

        // store.load({
        //    params: {
        //         // specify params for the first page load if using paging
        // //         start: 0,
        // //         limit: 10,
        //         // other params
        //         searchKeyword: ''
        //     },
        //     callback: function(records, operation, success) {
        //                 for(var index in records){
        //                     var isPass = records[index].get('isPass');
        //                     console.log("ispass:",isPass);
        // //                     if(isPass == 3){

        // //                     }
        //                 }
        //                 //form.loadRecord(recordIdeal);

        // //         var dldmvalue = records[0].get('dldm');
        // //         var dldm = Ext.getCmp('dldm');
        // //         dldm.setValue(dldmvalue);
        // //         console.log("dldmvalue:",dldmvalue);
        // //         console.log("dldm:",dldm);
        //     }
        // });
    }

});