/*
 * File: app/view/thematic_landuseValueCalculation.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.thematic_landuseValueCalculation', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.thematic_landuseValueCalculation',

    requires: [
        'Ext.form.Panel',
        'Ext.form.field.ComboBox',
        'Ext.form.field.Hidden',
        'Ext.form.FieldSet',
        'Ext.form.field.Number',
        'Ext.form.Label',
        'Ext.grid.Panel',
        'Ext.grid.column.RowNumberer',
        'Ext.grid.column.Date',
        'Ext.grid.column.Number',
        'Ext.grid.View',
        'Ext.toolbar.Toolbar',
        'Ext.toolbar.Separator',
        'Ext.button.Button'
    ],

    height: 588,
    width: 924,
    layout: 'border',
    title: '',
    defaultListenerScope: true,

    items: [
        {
            xtype: 'form',
            region: 'north',
            height: 150,
            hidden: true,
            id: 'survey_IndexCurrentValue_Form1',
            layout: 'absolute',
            bodyPadding: 10,
            jsonSubmit: true,
            items: [
                {
                    xtype: 'combobox',
                    x: 20,
                    y: 170,
                    id: 'survey_index_kfqTypeCombo1',
                    width: 340,
                    fieldLabel: '开发区评价类型',
                    name: 'kfqType',
                    allowBlank: false,
                    displayField: 'name',
                    store: 'landKfqTypeComboStore',
                    valueField: 'value'
                },
                {
                    xtype: 'hiddenfield',
                    x: 420,
                    y: 180,
                    id: 'survey_index_CalcNameText1',
                    fieldLabel: 'Label',
                    name: 'calcName'
                },
                {
                    xtype: 'fieldset',
                    height: 145,
                    width: 370,
                    layout: 'absolute',
                    title: '指标现状值',
                    items: [
                        {
                            xtype: 'numberfield',
                            x: 10,
                            y: 90,
                            id: 'survey_index_yjcczzmjText1',
                            width: 290,
                            fieldLabel: '建成城镇总面积',
                            name: 'jcczzmj',
                            allowBlank: false,
                            hideTrigger: true,
                            keyNavEnabled: false,
                            mouseWheelEnabled: false
                        },
                        {
                            xtype: 'numberfield',
                            x: 10,
                            y: 10,
                            id: 'survey_index_gkccmjText1',
                            width: 220,
                            fieldLabel: '工矿仓储面积',
                            name: 'gkcczmj',
                            allowBlank: false,
                            hideTrigger: true,
                            keyNavEnabled: false,
                            mouseWheelEnabled: false
                        },
                        {
                            xtype: 'numberfield',
                            x: 10,
                            y: 50,
                            id: 'survey_index_zzmjText1',
                            width: 220,
                            fieldLabel: '住宅用地面积',
                            name: 'zzzmj',
                            allowBlank: false,
                            hideTrigger: true,
                            keyNavEnabled: false,
                            mouseWheelEnabled: false
                        },
                        {
                            xtype: 'numberfield',
                            x: 240,
                            y: 10,
                            id: 'survey_index_gkccRateText1',
                            width: 100,
                            fieldLabel: '比例',
                            labelWidth: 30,
                            name: 'gkccRate',
                            allowBlank: false,
                            hideTrigger: true,
                            keyNavEnabled: false,
                            mouseWheelEnabled: false
                        },
                        {
                            xtype: 'numberfield',
                            x: 240,
                            y: 50,
                            id: 'survey_index_zzmjRateText1',
                            width: 100,
                            fieldLabel: '比例',
                            labelWidth: 30,
                            name: 'zzRate',
                            allowBlank: false,
                            hideTrigger: true,
                            keyNavEnabled: false,
                            mouseWheelEnabled: false
                        },
                        {
                            xtype: 'label',
                            x: 310,
                            y: 95,
                            text: '公顷'
                        }
                    ]
                },
                {
                    xtype: 'fieldset',
                    x: 420,
                    y: 10,
                    autoScroll: true,
                    height: 180,
                    width: 490,
                    layout: 'auto',
                    title: '指标计算',
                    items: [
                        {
                            xtype: 'textfield',
                            id: 'index_ygygyjsyd1',
                            width: 300,
                            fieldLabel: '已供应国有建设用地面积(D)',
                            labelWidth: 165,
                            submitValue: false
                        },
                        {
                            xtype: 'textfield',
                            id: 'index_ydgdtjtd1',
                            width: 300,
                            fieldLabel: '已达供地条件土地面积',
                            labelWidth: 165,
                            submitValue: false
                        },
                        {
                            xtype: 'textfield',
                            id: 'index_yjcczjsyd1',
                            width: 300,
                            fieldLabel: '已建成城镇建设用地面积',
                            labelWidth: 165,
                            submitValue: false
                        },
                        {
                            xtype: 'textfield',
                            id: 'index_gkccmj1',
                            width: 300,
                            fieldLabel: '工矿仓储面积',
                            labelWidth: 165,
                            submitValue: false
                        },
                        {
                            xtype: 'textfield',
                            id: 'index_zjzmj1',
                            width: 300,
                            fieldLabel: 'A总建筑面积（JZMJ）',
                            labelWidth: 165,
                            submitValue: false
                        },
                        {
                            xtype: 'textfield',
                            id: 'index_jzjdmj1',
                            width: 300,
                            fieldLabel: 'A建筑基地面积（JZJDMJ）',
                            labelWidth: 165,
                            submitValue: false
                        },
                        {
                            xtype: 'textfield',
                            id: 'index_gkzjzmj1',
                            width: 300,
                            fieldLabel: 'A2总建筑面积（JZMJ）',
                            labelWidth: 165,
                            submitValue: false
                        },
                        {
                            xtype: 'textfield',
                            id: 'index_gkjzjdmj1',
                            width: 300,
                            fieldLabel: 'A2建筑基地面积（JDZMJ）',
                            labelWidth: 165,
                            submitValue: false
                        },
                        {
                            xtype: 'textfield',
                            id: 'index_gdzctzze1',
                            width: 300,
                            fieldLabel: 'A固定资产投资（GDZCTZZE）',
                            labelWidth: 165,
                            submitValue: false
                        },
                        {
                            xtype: 'textfield',
                            id: 'index_gyssze1',
                            width: 300,
                            fieldLabel: 'A地均税收（GYSSZE）',
                            labelWidth: 165,
                            submitValue: false
                        }
                    ]
                }
            ]
        },
        {
            xtype: 'gridpanel',
            region: 'center',
            id: 'landuseValueGird',
            title: '开发区土地利用状况动态数据',
            store: 'landKfqTypeStore',
            columns: [
                {
                    xtype: 'rownumberer'
                },
                {
                    xtype: 'gridcolumn',
                    width: 209,
                    align: 'center',
                    dataIndex: 'calcName',
                    text: '名称'
                },
                {
                    xtype: 'datecolumn',
                    width: 100,
                    dataIndex: 'calcDate',
                    text: '时间',
                    format: 'Y-m-d'
                },
                {
                    xtype: 'gridcolumn',
                    width: 150,
                    dataIndex: 'kfqType',
                    text: '开发区类型'
                },
                {
                    xtype: 'gridcolumn',
                    width: 150,
                    dataIndex: 'kfqjb',
                    text: '开发区级别'
                },
                {
                    xtype: 'gridcolumn',
                    width: 150,
                    dataIndex: 'kfqsplx',
                    text: '开发区审批类型'
                },
                {
                    xtype: 'numbercolumn',
                    width: 150,
                    dataIndex: 'jcczzmj',
                    text: '建成城镇总面积/公顷'
                },
                {
                    xtype: 'numbercolumn',
                    width: 130,
                    dataIndex: 'gkcczmj',
                    text: '工矿仓储面积/公顷'
                },
                {
                    xtype: 'numbercolumn',
                    width: 120,
                    dataIndex: 'zzzmj',
                    text: '住宅面积/公顷'
                },
                {
                    xtype: 'numbercolumn',
                    width: 120,
                    dataIndex: 'ma3',
                    text: '交通运输用地/公顷'
                },
                {
                    xtype: 'numbercolumn',
                    width: 120,
                    dataIndex: 'ma4',
                    text: '商服用地/公顷'
                },
                {
                    xtype: 'numbercolumn',
                    width: 120,
                    dataIndex: 'ma5',
                    text: '公共管理与公共服务用地/公顷'
                },
                {
                    xtype: 'numbercolumn',
                    width: 120,
                    dataIndex: 'ma6',
                    text: '其他城镇建设用地/公顷'
                },
                {
                    xtype: 'numbercolumn',
                    width: 120,
                    dataIndex: 'mb',
                    text: '未建成城镇建设用地/公顷'
                },
                {
                    xtype: 'numbercolumn',
                    width: 120,
                    dataIndex: 'mc',
                    text: '不可建设土地/公顷'
                },
                {
                    xtype: 'numbercolumn',
                    dataIndex: 'md',
                    text: '已供应国有建设用地/公顷'
                },
                {
                    xtype: 'numbercolumn',
                    dataIndex: 'ME',
                    text: '尚可供地面积/公顷'
                },
                {
                    xtype: 'numbercolumn',
                    dataIndex: 'mf',
                    text: '不可供应土地/公顷'
                },
                {
                    xtype: 'numbercolumn',
                    dataIndex: 'da',
                    text: '发展区建成城镇总面积/公顷'
                },
                {
                    xtype: 'numbercolumn',
                    dataIndex: 'da2',
                    text: '发展区工矿仓储面积/公顷'
                },
                {
                    xtype: 'numbercolumn',
                    dataIndex: 'da1',
                    text: '发展区住宅面积/公顷'
                },
                {
                    xtype: 'numbercolumn',
                    dataIndex: 'da3',
                    text: '发展区交通用地/公顷'
                },
                {
                    xtype: 'numbercolumn',
                    dataIndex: 'da4',
                    text: '发展区商服用地/公顷'
                },
                {
                    xtype: 'numbercolumn',
                    dataIndex: 'da5',
                    text: '发展区公共管理与公共服务用地/公顷'
                },
                {
                    xtype: 'numbercolumn',
                    dataIndex: 'da6',
                    text: '发展区其他城镇建设用地/公顷'
                },
                {
                    xtype: 'numbercolumn',
                    dataIndex: 'db',
                    text: '发展区未建成城镇建设用地/公顷'
                },
                {
                    xtype: 'numbercolumn',
                    dataIndex: 'dc',
                    text: '发展区不可建设土地/公顷'
                },
                {
                    xtype: 'numbercolumn',
                    dataIndex: 'dd',
                    text: '发展区已供应国有建设用地/公顷'
                },
                {
                    xtype: 'numbercolumn',
                    dataIndex: 'de',
                    text: '发展区尚可供地面积/供应'
                },
                {
                    xtype: 'numbercolumn',
                    dataIndex: 'df',
                    text: '发展区不可供应土地/公顷'
                }
            ],
            dockedItems: [
                {
                    xtype: 'toolbar',
                    dock: 'top',
                    items: [
                        {
                            xtype: 'textfield',
                            id: 'land_KfqName_SearchText1',
                            emptyText: '请输入开发区名称搜索',
                            listeners: {
                                change: 'onLand_KfqName_SearchTextChange1'
                            }
                        },
                        {
                            xtype: 'tbseparator'
                        },
                        {
                            xtype: 'button',
                            hidden: true,
                            icon: 'images/table/preview.png',
                            text: '查看',
                            listeners: {
                                click: 'onButtonClick211'
                            }
                        },
                        {
                            xtype: 'button',
                            icon: 'images/table/delete.png',
                            text: '删除',
                            listeners: {
                                click: 'onButtonClick311'
                            }
                        }
                    ]
                }
            ]
        }
    ],
    dockedItems: [
        {
            xtype: 'toolbar',
            dock: 'top',
            items: [
                {
                    xtype: 'combobox',
                    id: 'survey_KfqArea_Combo',
                    fieldLabel: '选择地区',
                    submitValue: false,
                    displayField: 'name',
                    store: 'thematic_LCCT_KFQStore',
                    valueField: 'value',
                    listeners: {
                        change: 'onComboboxChange'
                    }
                },
                {
                    xtype: 'combobox',
                    id: 'survey_layerUrls_Combo',
                    width: 250,
                    fieldLabel: '选择年份',
                    labelWidth: 60,
                    name: '',
                    submitValue: false,
                    displayField: 'mapName',
                    store: 'survey_IndexCurrent_MapStore',
                    valueField: 'mapUrl'
                },
                {
                    xtype: 'button',
                    handler: function() {
                        //加入地图的js文件
                        var head = document.getElementsByTagName('head')[0];
                        var script= document.createElement("script");
                        script.type = "text/javascript";
                        script.src="mapjs/landuse_value_caculate.js";//survey_IndexCurrentValueCalculation_map.js";
                        head.appendChild(script);
                    },
                    text: '计算'
                },
                {
                    xtype: 'button',
                    handler: function() {
                        var myform = Ext.getCmp('survey_IndexCurrentValue_Form').getForm();
                        if (myform.isValid())
                        {
                            myform.submit({
                                url : 'add_landKfqType',
                                success : function (form, action)
                                {
                                    Ext.Msg.alert('成功', '本次计算结果添加成功。');
                                    var mystore = Ext.StoreMgr.get('landKfqTypeStore'); //获得store对象
                                    mystore.reload();
                                    myform.reset();
                                },
                                failure: function(form, action){
                                    Ext.Msg.alert('失败', '添加失败，请重试。');
                                }
                            });
                        }
                        else
                        {
                            Ext.Msg.alert('注意', '填写的信息有误，请检查！');
                        }
                    },
                    hidden: true,
                    text: '保存计算结果'
                },
                {
                    xtype: 'button',
                    handler: function(button, e) {
                        var  mystore=Ext.StoreMgr.get('zd_checkStore');
                        console.log(mystore.getCount());
                        mystore.filter("dldm", 'A');
                        console.log(mystore.getCount());
                        var store=new Ext.data.ArrayStore();
                        store=mystore;
                        console.log(store.getCount());

                        var yjcczzmj = store.sum("dlmj");
                        console.log(yjcczzmj);
                        store.clearFilter();
                        store.filter("dldm", 'A2');
                        store.filter("gysj", '2006-12');

                        console.log(store.getCount());
                        var mj = store.sum("dlmj");
                        console.log(mj);
                        store.clearFilter();
                        console.log(store.getCount());
                    },
                    hidden: true,
                    text: 'MyButton'
                }
            ]
        }
    ],
    listeners: {
        afterrender: 'onPanelAfterRender'
    },

    onLand_KfqName_SearchTextChange1: function(field, newValue, oldValue, eOpts) {
        //var searchKeyword = Ext.getCmp('land_KfqName_SearchText').getValue();
        var mystore = Ext.StoreMgr.get('landKfqTypeStore'); //获得store对象
        //在load事件中添加参数
        mystore.load({
            params :{searchKeyword : newValue}
        });
    },

    onButtonClick211: function(button, e, eOpts) {
        //获取数据
        var models = Ext.getCmp('monitor_Value_Gird').getSelection();
        if (models.length === 0){
            Ext.Msg.alert('提示', '请选择一条数据后再查看信息。');
            return;
        } else if(models.length >1){
            Ext.Msg.alert('提示', '每次只能查看一条信息，请重新选择。');
            return;
        }
        //启动窗口
        var win = Ext.widget('system_MapAddWindow');
        win.setTitle('修改信息');
        win.show();

        //改变Ajax url
        var form = Ext.getCmp('system_MapAddForm').getForm();
        form.loadRecord(models[0]);
        form.url = 'update_Map';
    },

    onButtonClick311: function(button, e, eOpts) {
        //获取数据
        var records = Ext.getCmp('landuseValueGird').getSelection();
        if (records.length === 0){
           Ext.Msg.alert('提示', '请选择一条数据后再点击删除按钮。');
           return;
        }
        var  ids =new Array(records.length);
        for(var i = 0;i<records.length;i++){
            ids[i] = records[i].get("id");
        }
        if(ids.length ==1){
            Ext.Msg.confirm('提示', '您正在删除：<br/>[' + records[0].get('calcName') +']<br/> 确认删除？', getResult);
        }else{
            Ext.Msg.confirm('提示', '您正在删除<br/>[' +ids.length+']组数据。<br/> 确认删除？', getResult);
        }


        function getResult(confirm)
        {
            console.log('confirm:', confirm);
            if (confirm == "yes"){
                Ext.Ajax.request(
                {
                    url : 'del_landKfqTypeById',
                    params :
                    {
                        ids : ids
                    },
                    success : function (response){
                        Ext.Msg.alert('成功提示', '记录删除成功。');
                        var mystore = Ext.StoreMgr.get('landKfqTypeStore');
                        mystore.reload();
                        //var myGrid=Ext.getCmp('landuseValueGrid');
                        //myGrid.reconfigure(mystore);
                    },
                    failure : function (response){
                        Ext.Msg.alert('失败提示', '记录删除失败。');
                    }
                });
            }
        }

    },

    onComboboxChange: function(field, newValue, oldValue, eOpts) {
        var store = Ext.StoreMgr.get('survey_IndexCurrent_MapStore');
        store.clearFilter();
        store.filter('mapKey',newValue);
    },

    onPanelAfterRender: function(component, eOpts) {
        var store=Ext.StoreMgr.get('landKfqTypeStore');
        store.reload();
    }

});