/*
 * File: app/view/thematic_LanduseConstructionChangeTrend.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.thematic_LanduseConstructionChangeTrend', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.thematic_LanduseConstructionChangeTrend',

    requires: [
        'Ext.tab.Panel',
        'Ext.grid.Panel',
        'Ext.grid.View',
        'Ext.grid.column.RowNumberer',
        'Ext.tab.Tab',
        'Ext.toolbar.Toolbar',
        'Ext.form.field.ComboBox'
    ],

    autoScroll: true,
    height: 741,
    width: 945,
    layout: 'border',
    title: '土地利用结构变化趋势分析',
    defaultListenerScope: true,

    items: [
        {
            xtype: 'tabpanel',
            region: 'center',
            id: 'landuseTable',
            activeTab: 0,
            items: [
                {
                    xtype: 'panel',
                    id: 'landuse_jzzk',
                    layout: 'border',
                    title: '用地现状统计',
                    items: [
                        {
                            xtype: 'panel',
                            region: 'center',
                            split: true,
                            html: '<div id = "thematic_LanduseConstructionChangeTrend_echart" class="echartsDiv"></div>',
                            layout: 'fit',
                            listeners: {
                                afterrender: 'onPanelAfterRender1'
                            }
                        },
                        {
                            xtype: 'gridpanel',
                            region: 'south',
                            split: true,
                            height: 150,
                            id: 'thematic_jzzk_Grid',
                            collapsed: true,
                            collapsible: true,
                            title: '历年土地建设状况统计数据',
                            columns: [
                                {
                                    xtype: 'rownumberer'
                                }
                            ],
                            listeners: {
                                activate: 'onThematic_LCCT_GridActivate'
                            }
                        }
                    ],
                    listeners: {
                        activate: 'onPanelActivate'
                    }
                },
                {
                    xtype: 'panel',
                    hidden: true,
                    id: 'landuse_gyzk',
                    layout: 'border',
                    title: '土地供应状况',
                    items: [
                        {
                            xtype: 'panel',
                            region: 'center',
                            split: true,
                            html: '<div id = "thematic_LanduseConstructionChangeTrend_GYLX_echart" class="echartsDiv"></div>',
                            layout: 'fit'
                        },
                        {
                            xtype: 'gridpanel',
                            region: 'south',
                            split: true,
                            height: 150,
                            id: 'thematic_gyzk_Grid',
                            title: '历年土地供应状况统计数据',
                            columns: [
                                {
                                    xtype: 'rownumberer'
                                }
                            ]
                        }
                    ],
                    listeners: {
                        activate: 'onPanelActivate1'
                    }
                }
            ]
        }
    ],
    dockedItems: [
        {
            xtype: 'toolbar',
            dock: 'top',
            items: [
                {
                    xtype: 'combobox',
                    id: 'the_statisticType',
                    width: 250,
                    fieldLabel: '选择统计类型',
                    value: '',
                    displayField: 'name',
                    store: 'landKfqNow',
                    valueField: 'value',
                    listeners: {
                        change: 'onThe_statisticTypeChange'
                    }
                },
                {
                    xtype: 'combobox',
                    id: 'thematicLCCT_StartYearCombo',
                    renderData: 'return [\n    {"name": "2016","value": "2016"},\n    {"name": "2015","value": "2015"},\n    {"name": "2014","value": "2014"},\n    {"name": "2013","value": "2013"},\n    {"name": "2012","value": "2012"},\n    {"name": "2011","value": "2011"},\n    {"name": "2010","value": "2010"}\n];',
                    width: 150,
                    fieldLabel: '起始年份',
                    labelWidth: 60,
                    value: '2013',
                    autoLoadOnValue: true,
                    displayField: 'name',
                    store: 'tmematic_LCCT_StartYearStore',
                    valueField: 'value',
                    valueNotFoundText: '时间超出范围'
                },
                {
                    xtype: 'combobox',
                    id: 'thematicLCCT_EndYearCombo',
                    renderData: 'return [\n    {"name": "2016","value": "2016"},\n    {"name": "2015","value": "2015"},\n    {"name": "2014","value": "2014"},\n    {"name": "2013","value": "2013"},\n    {"name": "2012","value": "2012"},\n    {"name": "2011","value": "2011"},\n    {"name": "2010","value": "2010"}\n];',
                    width: 150,
                    fieldLabel: '截止年份',
                    labelWidth: 60,
                    value: '2013',
                    autoLoadOnValue: true,
                    displayField: 'name',
                    store: 'tmematic_LCCT_EndYearStore',
                    valueField: 'value'
                },
                {
                    xtype: 'button',
                    hidden: true,
                    id: 'thematicLCCT_SubmitButton',
                    text: '开始分析'
                },
                {
                    xtype: 'button',
                    handler: function(button, e) {
                        //加入地图的js文件
                        var head = document.getElementsByTagName('head')[0];
                        var script= document.createElement("script");
                        script.type = "text/javascript";
                        script.src="mapjs/thematic_LanduseConstructionClassicStatistic.js";//thematic_LanduseConstructionChangeTrend_map.js
                        head.appendChild(script);
                        Ext.Msg.alert('提示',"统计完成！");
                    },
                    text: '开始统计'
                }
            ]
        },
        {
            xtype: 'toolbar',
            dock: 'top',
            items: [
                {
                    xtype: 'combobox',
                    id: 'the_kfqZoneCombo',
                    width: 202,
                    fieldLabel: '选择区域',
                    labelWidth: 80,
                    store: [
                        '黑龙江省',
                        '哈尔滨市',
                        '牡丹江市',
                        '大庆市',
                        '双鸭山市',
                        '绥化市',
                        '黑河市',
                        '齐齐哈尔市',
                        '佳木斯市',
                        '鸡西市',
                        '伊春市',
                        '七台河市',
                        '鹤岗市',
                        '大兴安岭地区'
                    ],
                    valueField: 'mapUrl'
                },
                {
                    xtype: 'combobox',
                    id: 'the_kfqGradeCombo',
                    width: 202,
                    fieldLabel: '开发区级别',
                    labelWidth: 80,
                    store: [
                        '国家级',
                        '省级',
                        '省级以下'
                    ],
                    valueField: 'mapUrl'
                },
                {
                    xtype: 'combobox',
                    id: 'the_kfqtypeCombo',
                    width: 250,
                    fieldLabel: '开发区评价类型',
                    store: [
                        '工业主导型开发区',
                        '产城融合型开发区'
                    ],
                    valueField: 'mapUrl',
                    listeners: {
                        change: 'onThe_kfqtypeComboChange'
                    }
                },
                {
                    xtype: 'combobox',
                    id: 'the_kfqSpTypeCombo',
                    width: 250,
                    fieldLabel: '开发区审批类型',
                    displayField: 'name',
                    store: 'landKfqSpTypeComboStore',
                    valueField: 'value',
                    listeners: {
                        change: 'onThe_kfqtypeComboChange1'
                    }
                }
            ]
        },
        {
            xtype: 'toolbar',
            dock: 'top',
            items: [
                {
                    xtype: 'combobox',
                    id: 'the_kfqNameCombo',
                    width: 268,
                    fieldLabel: '选择开发区',
                    labelWidth: 80,
                    displayField: 'calcName',
                    store: 'landKfqTypeStore',
                    valueField: 'kfqsplx'
                },
                {
                    xtype: 'combobox',
                    id: 'the_kfqRangeCombo',
                    width: 230,
                    fieldLabel: '选择开发区评价范围',
                    labelWidth: 130,
                    value: '主区',
                    displayField: 'calcName',
                    store: [
                        '主区',
                        '发展区'
                    ]
                }
            ]
        }
    ],

    onPanelAfterRender1: function(component, eOpts) {
        /*var head = document.getElementsByTagName('head')[0];
        var script= document.createElement("script");
        script.type = "text/javascript";
        script.src="echarts/thematic_LanduseConstructionChange_DLMC.js";//"mapjs/dataImport.js";//
        head.appendChild(script);*/
    },

    onThematic_LCCT_GridActivate: function(component, eOpts) {

    },

    onPanelActivate: function(component, eOpts) {

        // //thematic_LanduseConstructionChange_dlmcCaculate_map//thematic_LanduseConstructionChange_DLMC_map
        // var head = document.getElementsByTagName('head')[0];
        //         var script= document.createElement("script");
        //         script.type = "text/javascript";
        //         script.src="mapjs/thematic_LanduseConstructionChange_dlmcCaculate_map.js";//"mapjs/dataImport.js";//
        //         head.appendChild(script);
        // var head = document.getElementsByTagName('head')[0];
        // var script= document.createElement("script");
        // script.type = "text/javascript";
        // script.src="echarts/thematic_LanduseConstructionChange_DLMC.js";//"mapjs/dataImport.js";//
        // head.appendChild(script);
    },

    onPanelActivate1: function(component, eOpts) {

        var kfqType = Ext.getCmp('the_kfqtypeCombo').getValue();
        console.log("开发区类型是："+kfqType);
        // var head = document.getElementsByTagName('head')[0];
        //         var script= document.createElement("script");
        //         script.type = "text/javascript";
        //         script.src="mapjs/thematic_LanduseConstructionChange_GYLX_map.js";//"mapjs/dataImport.js";//
        //         head.appendChild(script);
        // var head = document.getElementsByTagName('head')[0];
        // var script= document.createElement("script");
        // script.type = "text/javascript";
        // script.src="echarts/thematic_LanduseConstructionChange_GYLX.js";//"mapjs/dataImport.js";//
        // head.appendChild(script);
    },

    onThe_statisticTypeChange: function(field, newValue, oldValue, eOpts) {
        var value=Ext.getCmp('the_statisticType').getRawValue();
        Ext.getCmp('landuse_jzzk').setTitle(value);
    },

    onThe_kfqtypeComboChange: function(field, newValue, oldValue, eOpts) {


    },

    onThe_kfqtypeComboChange1: function(field, newValue, oldValue, eOpts) {

    }

});