/*
 * File: app/view/thematic_LanduseIndexValue.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.thematic_LanduseIndexValue', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.thematic_LanduseIndexValue',

    requires: [
        'Ext.tab.Panel',
        'Ext.grid.Panel',
        'Ext.grid.View',
        'Ext.grid.column.RowNumberer',
        'Ext.tab.Tab',
        'Ext.toolbar.Toolbar',
        'Ext.form.field.ComboBox'
    ],

    autoScroll: true,
    height: 741,
    width: 786,
    layout: 'border',
    title: '开发区评价指标变化统计分析',
    defaultListenerScope: true,

    items: [
        {
            xtype: 'tabpanel',
            region: 'center',
            activeTab: 0,
            items: [
                {
                    xtype: 'panel',
                    layout: 'border',
                    title: '评价指标统计',
                    items: [
                        {
                            xtype: 'panel',
                            region: 'center',
                            split: true,
                            html: '<div id = "thematic_LanduseIndexValue_echart" class="echartsDiv"></div>',
                            layout: 'fit',
                            listeners: {
                                afterrender: 'onPanelAfterRender1'
                            }
                        },
                        {
                            xtype: 'gridpanel',
                            region: 'south',
                            split: true,
                            height: 150,
                            id: 'thematic_LanduseIndexValue_Grid',
                            collapsed: true,
                            collapsible: true,
                            title: '历年评价指标值统计数据',
                            columns: [
                                {
                                    xtype: 'rownumberer'
                                }
                            ],
                            listeners: {
                                activate: 'onThematic_LCCT_GridActivate'
                            }
                        }
                    ],
                    listeners: {
                        activate: 'onPanelActivate'
                    }
                }
            ]
        }
    ],
    dockedItems: [
        {
            xtype: 'toolbar',
            dock: 'top',
            items: [
                {
                    xtype: 'combobox',
                    hidden: true,
                    id: 'thematicIndexType_KFQCombo',
                    width: 163,
                    fieldLabel: '指标类型',
                    labelWidth: 60,
                    store: [
                        '指标现状值',
                        '指标标准化'
                    ],
                    valueField: 'kfqType'
                },
                {
                    xtype: 'combobox',
                    id: 'thematicIndexValue_KFQCombo',
                    renderData: 'return [\n    {"name": "2016","value": "2016"},\n    {"name": "2015","value": "2015"},\n    {"name": "2014","value": "2014"},\n    {"name": "2013","value": "2013"},\n    {"name": "2012","value": "2012"},\n    {"name": "2011","value": "2011"},\n    {"name": "2010","value": "2010"}\n];',
                    width: 250,
                    fieldLabel: '开发区',
                    labelWidth: 60,
                    autoLoadOnValue: true,
                    displayField: 'kfqName',
                    store: 'landIndexIntensityValueStore',
                    valueField: 'kfqType'
                },
                {
                    xtype: 'combobox',
                    id: 'thematicLCCT_StartYearCombo1',
                    renderData: 'return [\n    {"name": "2016","value": "2016"},\n    {"name": "2015","value": "2015"},\n    {"name": "2014","value": "2014"},\n    {"name": "2013","value": "2013"},\n    {"name": "2012","value": "2012"},\n    {"name": "2011","value": "2011"},\n    {"name": "2010","value": "2010"}\n];',
                    width: 150,
                    fieldLabel: '起始年份',
                    labelWidth: 60,
                    value: '2012',
                    autoLoadOnValue: true,
                    displayField: 'name',
                    store: 'tmematic_LCCT_StartYearStore',
                    valueField: 'value',
                    valueNotFoundText: '时间超出范围'
                },
                {
                    xtype: 'combobox',
                    id: 'thematicLCCT_EndYearCombo1',
                    renderData: 'return [\n    {"name": "2016","value": "2016"},\n    {"name": "2015","value": "2015"},\n    {"name": "2014","value": "2014"},\n    {"name": "2013","value": "2013"},\n    {"name": "2012","value": "2012"},\n    {"name": "2011","value": "2011"},\n    {"name": "2010","value": "2010"}\n];',
                    width: 150,
                    fieldLabel: '截止年份',
                    labelWidth: 60,
                    value: '2013',
                    autoLoadOnValue: true,
                    displayField: 'name',
                    store: 'tmematic_LCCT_EndYearStore',
                    valueField: 'value'
                },
                {
                    xtype: 'button',
                    handler: function(button, e) {
                        var head = document.getElementsByTagName('head')[0];
                        var script= document.createElement("script");
                        script.type = "text/javascript";
                        script.src="mapjs/thematic_LanduseEvaluationIndex_NO1_map.js";//"mapjs/dataImport.js";//
                        head.appendChild(script);
                    },
                    id: 'thematicLCCT_SubmitButton1',
                    text: '统计分析'
                },
                {
                    xtype: 'button',
                    handler: function(button, e) {
                        //加入地图的js文件
                        var head = document.getElementsByTagName('head')[0];
                        var script= document.createElement("script");
                        script.type = "text/javascript";
                        script.src="mapjs/thematic_LanduseConstructionClassicStatistic.js";//thematic_LanduseConstructionChangeTrend_map.js
                        head.appendChild(script);
                        Ext.Msg.alert("提示","同步完成");
                    },
                    hidden: true,
                    text: '测试导入数据库'
                }
            ]
        }
    ],

    onPanelAfterRender1: function(component, eOpts) {
        /*var head = document.getElementsByTagName('head')[0];
        var script= document.createElement("script");
        script.type = "text/javascript";
        script.src="echarts/thematic_LanduseConstructionChange_DLMC.js";//"mapjs/dataImport.js";//
        head.appendChild(script);*/
    },

    onThematic_LCCT_GridActivate: function(component, eOpts) {

    },

    onPanelActivate: function(component, eOpts) {
        /*
        var head = document.getElementsByTagName('head')[0];
                var script= document.createElement("script");
                script.type = "text/javascript";
                script.src="mapjs/thematic_LanduseConstructionChange_DLMC_map.js";//"mapjs/dataImport.js";//
                head.appendChild(script);
        var head = document.getElementsByTagName('head')[0];
        var script= document.createElement("script");
        script.type = "text/javascript";
        script.src="echarts/thematic_LanduseConstructionChange_DLMC.js";//"mapjs/dataImport.js";//
        head.appendChild(script);*/
    }

});