/*
 * File: app/view/zdxx_change.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.zdxx_change', {
    extend: 'Ext.window.Window',
    alias: 'widget.zdxx_change',

    requires: [
        'MyApp.view.zdxx_changeViewModel',
        'Ext.toolbar.Toolbar',
        'Ext.button.Button',
        'Ext.toolbar.Fill',
        'Ext.form.Panel',
        'Ext.form.field.TextArea',
        'Ext.form.field.Number'
    ],

    viewModel: {
        type: 'zdxx_change'
    },
    height: 535,
    id: 'zdxx_change',
    width: 487,
    layout: 'border',
    collapseFirst: false,
    title: '宗地数据更新详单',

    dockedItems: [
        {
            xtype: 'toolbar',
            dock: 'bottom',
            items: [
                {
                    xtype: 'button',
                    hidden: true,
                    text: '通过变更'
                },
                {
                    xtype: 'tbfill'
                },
                {
                    xtype: 'button',
                    handler: function(button, e) {
                        var win = Ext.getCmp('zdxx_change');
                        var myform = Ext.getCmp('zdxx_nowadayData').getForm();



                        if (myform.isValid())
                        {
                            myform.submit({
                                url : 'update_zdInfo',
                                success : function (form, action)
                                {
                                    Ext.Msg.alert('成功', '宗地信息更新成功');

                                    var mystore = Ext.StoreMgr.get('zd_infoStore'); //获得store对象
                                    mystore.reload();
                                    win.close();
                                },
                                failure: function(form, action){
                                    Ext.Msg.alert('失败', '宗地信息更新失败');
                                    win.close();
                                }
                            });
                        }
                        else{
                            Ext.Msg.alert('注意', '填写的信息有误，请检查！');
                        }

                        return;
                    },
                    icon: 'images/table/upload.png',
                    text: '提交'
                },
                {
                    xtype: 'button',
                    icon: 'images/table/delete2.png',
                    text: '取消'
                }
            ]
        }
    ],
    items: [
        {
            xtype: 'form',
            region: 'north',
            height: 205,
            hidden: true,
            id: 'ent_landuseChangeAttr_Form1',
            layout: 'form',
            bodyPadding: 10,
            items: [
                {
                    xtype: 'textfield',
                    fieldLabel: '审核状态',
                    labelWidth: 80,
                    name: 'shzt'
                },
                {
                    xtype: 'textareafield',
                    fieldLabel: '审核意见',
                    labelWidth: 80,
                    name: 'shyj'
                },
                {
                    xtype: 'textfield',
                    fieldLabel: '采集人',
                    labelWidth: 80,
                    name: 'cjr'
                },
                {
                    xtype: 'textfield',
                    fieldLabel: '采集时间',
                    labelWidth: 80,
                    name: 'cjsj'
                }
            ]
        },
        {
            xtype: 'panel',
            flex: 1,
            region: 'center',
            autoScroll: true,
            layout: 'border',
            manageHeight: false,
            items: [
                {
                    xtype: 'form',
                    flex: 1,
                    region: 'center',
                    id: 'zdxx_historyData',
                    maxHeight: 1000,
                    minHeight: 1000,
                    bodyPadding: 10,
                    manageHeight: false,
                    title: '历史数据资料',
                    titleAlign: 'right',
                    layout: {
                        type: 'vbox',
                        align: 'stretch'
                    },
                    items: [
                        {
                            xtype: 'textfield',
                            fieldLabel: '目标识别码',
                            labelWidth: 90,
                            name: 'mbbsm'
                        },
                        {
                            xtype: 'textfield',
                            fieldLabel: '要素代码',
                            labelWidth: 90,
                            name: 'ysdm'
                        },
                        {
                            xtype: 'textfield',
                            width: 150,
                            fieldLabel: '开发区代码',
                            labelWidth: 90,
                            name: 'kfqdm'
                        },
                        {
                            xtype: 'textfield',
                            width: 150,
                            fieldLabel: '开发区名称',
                            labelWidth: 90,
                            name: 'kfqmc'
                        },
                        {
                            xtype: 'textfield',
                            width: 150,
                            fieldLabel: '评价范围',
                            labelWidth: 90,
                            name: 'kfqpjfw'
                        },
                        {
                            xtype: 'textfield',
                            width: 150,
                            fieldLabel: '图斑编号',
                            labelWidth: 90,
                            name: 'tbbh'
                        },
                        {
                            xtype: 'textfield',
                            width: 150,
                            fieldLabel: '供应时间',
                            labelWidth: 90,
                            name: 'gysj'
                        },
                        {
                            xtype: 'textfield',
                            width: 150,
                            fieldLabel: '使用年限',
                            labelWidth: 90,
                            name: 'synx'
                        },
                        {
                            xtype: 'textfield',
                            width: 150,
                            fieldLabel: '权属',
                            labelWidth: 90,
                            name: 'qs'
                        },
                        {
                            xtype: 'textfield',
                            width: 150,
                            fieldLabel: '土地使用者',
                            labelWidth: 90,
                            name: 'tdsyz'
                        },
                        {
                            xtype: 'textfield',
                            width: 150,
                            fieldLabel: '用地类型',
                            labelWidth: 90,
                            name: 'dlmc',
                            submitValue: false
                        },
                        {
                            xtype: 'textfield',
                            width: 150,
                            fieldLabel: '地类面积',
                            labelWidth: 90,
                            name: 'dlmj',
                            submitValue: false
                        },
                        {
                            xtype: 'textfield',
                            width: 150,
                            fieldLabel: '建筑面积',
                            labelWidth: 90,
                            name: 'jzmj',
                            submitValue: false
                        },
                        {
                            xtype: 'textfield',
                            width: 150,
                            fieldLabel: '建筑基地面积',
                            labelWidth: 90,
                            name: 'jzjdmj',
                            submitValue: false
                        },
                        {
                            xtype: 'textfield',
                            width: 150,
                            fieldLabel: '构筑基地面积',
                            labelWidth: 90,
                            name: 'jdzmj',
                            submitValue: false
                        },
                        {
                            xtype: 'textfield',
                            width: 150,
                            fieldLabel: '高新类别',
                            labelWidth: 90,
                            name: 'gxlb',
                            submitValue: false
                        },
                        {
                            xtype: 'textfield',
                            width: 150,
                            fieldLabel: '高新用地面积',
                            labelWidth: 90,
                            name: 'gxydmj',
                            submitValue: false
                        },
                        {
                            xtype: 'textfield',
                            width: 150,
                            fieldLabel: '高新收入',
                            labelWidth: 90,
                            name: 'gxsr',
                            submitValue: false
                        },
                        {
                            xtype: 'textfield',
                            width: 150,
                            fieldLabel: '高新税收',
                            labelWidth: 90,
                            name: 'gxss',
                            submitValue: false
                        },
                        {
                            xtype: 'textareafield',
                            width: 150,
                            fieldLabel: '备注',
                            labelWidth: 90,
                            name: 'bz'
                        },
                        {
                            xtype: 'textfield',
                            hidden: true,
                            width: 150,
                            fieldLabel: '建筑系数/%',
                            labelWidth: 90,
                            name: 'id'
                        }
                    ]
                },
                {
                    xtype: 'form',
                    flex: 1,
                    region: 'east',
                    id: 'zdxx_nowadayData',
                    maxHeight: 1000,
                    maxWidth: 200,
                    minHeight: 1000,
                    width: 80,
                    layout: 'fit',
                    bodyPadding: 10,
                    title: '今年填报资料',
                    items: [
                        {
                            xtype: 'container',
                            layout: {
                                type: 'vbox',
                                align: 'stretch'
                            },
                            items: [
                                {
                                    xtype: 'textfield',
                                    name: 'mbbsm'
                                },
                                {
                                    xtype: 'textfield',
                                    labelWidth: 90,
                                    name: 'ysdm'
                                },
                                {
                                    xtype: 'textfield',
                                    labelWidth: 90,
                                    name: 'kfqdm'
                                },
                                {
                                    xtype: 'textfield',
                                    width: 60,
                                    labelWidth: 90,
                                    name: 'kfqmc'
                                },
                                {
                                    xtype: 'textfield',
                                    width: 60,
                                    labelWidth: 90,
                                    name: 'kfqpjfw'
                                },
                                {
                                    xtype: 'textfield',
                                    width: 60,
                                    labelWidth: 90,
                                    name: 'tbbh'
                                },
                                {
                                    xtype: 'textfield',
                                    width: 60,
                                    fieldLabel: '',
                                    labelWidth: 90,
                                    name: 'gysj'
                                },
                                {
                                    xtype: 'textfield',
                                    width: 60,
                                    labelWidth: 90,
                                    name: 'synx'
                                },
                                {
                                    xtype: 'textfield',
                                    width: 60,
                                    fieldLabel: '',
                                    labelWidth: 90,
                                    name: 'qs'
                                },
                                {
                                    xtype: 'textfield',
                                    width: 60,
                                    labelWidth: 90,
                                    name: 'tdsyz'
                                },
                                {
                                    xtype: 'textfield',
                                    width: 60,
                                    labelWidth: 90,
                                    name: 'dlmc'
                                },
                                {
                                    xtype: 'numberfield',
                                    width: 60,
                                    labelWidth: 90,
                                    name: 'dlmj'
                                },
                                {
                                    xtype: 'numberfield',
                                    width: 60,
                                    labelWidth: 90,
                                    name: 'jzmj'
                                },
                                {
                                    xtype: 'numberfield',
                                    width: 60,
                                    labelWidth: 90,
                                    name: 'jzjdmj'
                                },
                                {
                                    xtype: 'numberfield',
                                    width: 60,
                                    fieldLabel: '',
                                    labelWidth: 90,
                                    name: 'jdzmj'
                                },
                                {
                                    xtype: 'textfield',
                                    width: 60,
                                    labelWidth: 90,
                                    name: 'gxlb'
                                },
                                {
                                    xtype: 'numberfield',
                                    width: 60,
                                    labelWidth: 90,
                                    name: 'gxydmj'
                                },
                                {
                                    xtype: 'numberfield',
                                    width: 60,
                                    labelWidth: 90,
                                    name: 'gxsr'
                                },
                                {
                                    xtype: 'numberfield',
                                    width: 60,
                                    labelWidth: 90,
                                    name: 'gxss'
                                },
                                {
                                    xtype: 'textareafield',
                                    width: 60,
                                    labelWidth: 80,
                                    name: 'bz'
                                },
                                {
                                    xtype: 'textfield',
                                    hidden: true,
                                    width: 60,
                                    labelWidth: 90,
                                    name: 'id'
                                }
                            ]
                        }
                    ]
                }
            ]
        }
    ]

});