/*
 * File: app/view/zdxx_add.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.zdxx_add', {
    extend: 'Ext.window.Window',
    alias: 'widget.zdxx_add',

    requires: [
        'MyApp.view.zdxx_addViewModel',
        'Ext.tab.Panel',
        'Ext.tab.Tab',
        'Ext.form.Panel',
        'Ext.toolbar.Toolbar',
        'Ext.toolbar.Fill',
        'Ext.toolbar.Spacer',
        'Ext.form.field.ComboBox',
        'Ext.form.field.Number',
        'Ext.form.field.Date',
        'Ext.form.field.TextArea',
        'Ext.form.field.Hidden'
    ],

    viewModel: {
        type: 'zdxx_add'
    },
    height: 539,
    id: 'zdxx_add1',
    width: 825,
    layout: 'border',
    title: '添加宗地信息',
    defaultListenerScope: true,

    items: [
        {
            xtype: 'tabpanel',
            region: 'center',
            id: 'zdinformation',
            activeTab: 0,
            items: [
                {
                    xtype: 'panel',
                    height: 779,
                    id: 'title1',
                    title: '已建成建设用地',
                    items: [
                        {
                            xtype: 'form',
                            autoScroll: true,
                            height: 454,
                            id: 'add_zdwidinfo1',
                            layout: 'absolute',
                            bodyPadding: 10,
                            title: '',
                            jsonSubmit: true,
                            url: 'add_zdinfo',
                            items: [
                                {
                                    xtype: 'textfield',
                                    x: 20,
                                    y: 510,
                                    hidden: true,
                                    width: 220,
                                    fieldLabel: '开发区名称',
                                    name: 'id'
                                },
                                {
                                    xtype: 'textfield',
                                    x: 20,
                                    y: 10,
                                    width: 220,
                                    fieldLabel: '开发区名称',
                                    name: 'kfqmc',
                                    allowBlank: false,
                                    editable: false
                                },
                                {
                                    xtype: 'textfield',
                                    x: 290,
                                    y: 10,
                                    width: 220,
                                    fieldLabel: '图斑编号',
                                    name: 'tbbh',
                                    allowBlank: false
                                },
                                {
                                    xtype: 'combobox',
                                    x: 20,
                                    y: 40,
                                    width: 220,
                                    fieldLabel: '开发区评价范围',
                                    name: 'kfqpjfw',
                                    allowBlank: false,
                                    store: [
                                        '主区',
                                        '发展方向区'
                                    ]
                                },
                                {
                                    xtype: 'combobox',
                                    x: 290,
                                    y: 40,
                                    width: 220,
                                    fieldLabel: '开发区评价类型',
                                    name: 'kfqpjlx',
                                    allowBlank: false,
                                    store: [
                                        '工业主导型',
                                        '产城融合型'
                                    ]
                                },
                                {
                                    xtype: 'combobox',
                                    x: 20,
                                    y: 100,
                                    id: 'dlmc',
                                    width: 220,
                                    fieldLabel: '地类名称',
                                    name: 'dlmc',
                                    store: [
                                        '住宅用地',
                                        '工矿仓储用地',
                                        '街巷用地',
                                        '其他交通运输用地',
                                        '商服用地',
                                        '公园与绿地',
                                        '其他公共管理与公共服务用地',
                                        '其他城镇建设用地'
                                    ],
                                    listeners: {
                                        change: 'onDlmcChange'
                                    }
                                },
                                {
                                    xtype: 'numberfield',
                                    x: 290,
                                    y: 100,
                                    width: 220,
                                    fieldLabel: '地类面积(公顷)',
                                    name: 'dlmj',
                                    emptyText: '0',
                                    hideTrigger: true
                                },
                                {
                                    xtype: 'combobox',
                                    x: 550,
                                    y: 10,
                                    width: 220,
                                    fieldLabel: '权属',
                                    name: 'qs',
                                    allowBlank: false,
                                    emptyText: '',
                                    store: [
                                        '国有'
                                    ]
                                },
                                {
                                    xtype: 'datefield',
                                    x: 20,
                                    y: 70,
                                    width: 220,
                                    fieldLabel: '供应时间',
                                    name: 'gysj',
                                    allowBlank: false,
                                    format: 'Y-m'
                                },
                                {
                                    xtype: 'combobox',
                                    x: 550,
                                    y: 70,
                                    id: 'gylx',
                                    width: 220,
                                    fieldLabel: '供应类型',
                                    name: 'gylx',
                                    store: [
                                        '划拨土地',
                                        '有偿使用且未到期土地',
                                        '有偿使用且已到期但未处置土地'
                                    ],
                                    listeners: {
                                        change: 'onGylxChange'
                                    }
                                },
                                {
                                    xtype: 'combobox',
                                    x: 550,
                                    y: 40,
                                    width: 220,
                                    fieldLabel: '土地招拍佳情况',
                                    name: 'tdzpg',
                                    allowBlank: false,
                                    store: [
                                        '是',
                                        '否'
                                    ]
                                },
                                {
                                    xtype: 'textfield',
                                    x: 290,
                                    y: 70,
                                    width: 220,
                                    fieldLabel: '使用年限',
                                    name: 'synx'
                                },
                                {
                                    xtype: 'numberfield',
                                    x: 550,
                                    y: 100,
                                    width: 220,
                                    fieldLabel: '建筑面积(平方米)',
                                    name: 'jzmj',
                                    allowBlank: false,
                                    emptyText: '0',
                                    hideTrigger: true
                                },
                                {
                                    xtype: 'numberfield',
                                    x: 20,
                                    y: 135,
                                    width: 220,
                                    fieldLabel: '建筑基底面积(平方米)',
                                    name: 'jzjdmj',
                                    allowBlank: false,
                                    emptyText: '0',
                                    hideTrigger: true
                                },
                                {
                                    xtype: 'numberfield',
                                    x: 285,
                                    y: 135,
                                    width: 490,
                                    fieldLabel: '建筑物、构筑物基底及露天堆场、露天操作场地的总面积（平方米）',
                                    labelWidth: 390,
                                    name: 'jdzmj',
                                    emptyText: '0',
                                    hideTrigger: true
                                },
                                {
                                    xtype: 'combobox',
                                    x: 20,
                                    y: 175,
                                    width: 220,
                                    fieldLabel: '高新技术产业用地类别',
                                    name: 'gxlb',
                                    store: [
                                        '一类',
                                        '二类'
                                    ],
                                    listeners: {
                                        change: 'onComboboxChange5'
                                    }
                                },
                                {
                                    xtype: 'numberfield',
                                    x: 290,
                                    y: 175,
                                    width: 220,
                                    fieldLabel: '高新技术产业用地面积(公顷）',
                                    name: 'gxydmj',
                                    emptyText: '0',
                                    hideTrigger: true
                                },
                                {
                                    xtype: 'numberfield',
                                    x: 550,
                                    y: 175,
                                    width: 220,
                                    fieldLabel: '高新技术产业用地面积折算比例 ',
                                    name: 'gxzsbl',
                                    hideTrigger: true
                                },
                                {
                                    xtype: 'numberfield',
                                    x: 20,
                                    y: 215,
                                    width: 220,
                                    fieldLabel: '高新技术产业收入（万元）',
                                    name: 'gxsr',
                                    emptyText: '0',
                                    hideTrigger: true
                                },
                                {
                                    xtype: 'numberfield',
                                    x: 290,
                                    y: 215,
                                    width: 220,
                                    fieldLabel: '高新技术产业税收（万元）',
                                    name: 'gxss',
                                    emptyText: '0',
                                    hideTrigger: true
                                },
                                {
                                    xtype: 'combobox',
                                    x: 550,
                                    y: 215,
                                    id: 'ghyt',
                                    width: 220,
                                    fieldLabel: '规划用途',
                                    name: 'ghyt',
                                    store: [
                                        '住宅用地',
                                        '工矿仓储用地',
                                        '街巷用地',
                                        '其他交通运输用地',
                                        '商服用地',
                                        '公园与绿地',
                                        '其他公共管理与公共服务用地',
                                        '其他城镇建设用地'
                                    ],
                                    listeners: {
                                        change: 'onGhytChange'
                                    }
                                },
                                {
                                    xtype: 'numberfield',
                                    x: 20,
                                    y: 255,
                                    width: 490,
                                    fieldLabel: '工业企业、工业物流企业固定资产投资总额(万元）',
                                    labelWidth: 330,
                                    name: 'gdzctzze',
                                    emptyText: '0',
                                    hideTrigger: true
                                },
                                {
                                    xtype: 'numberfield',
                                    x: 550,
                                    y: 255,
                                    width: 220,
                                    fieldLabel: '二、三产业税收总额（万元/年）',
                                    name: 'esssze',
                                    emptyText: '0',
                                    hideTrigger: true
                                },
                                {
                                    xtype: 'numberfield',
                                    x: 20,
                                    y: 285,
                                    width: 220,
                                    fieldLabel: '工业企业工业物流企业总收入（万元/年）',
                                    labelWidth: 130,
                                    name: 'qyzsr',
                                    emptyText: '0',
                                    hideTrigger: true
                                },
                                {
                                    xtype: 'numberfield',
                                    x: 290,
                                    y: 285,
                                    width: 220,
                                    fieldLabel: '工业企业工业物流企业税收总额（万元/年）',
                                    labelWidth: 130,
                                    name: 'qyssze',
                                    emptyText: '0',
                                    hideTrigger: true
                                },
                                {
                                    xtype: 'textareafield',
                                    x: 20,
                                    y: 325,
                                    width: 750,
                                    fieldLabel: '备注',
                                    name: 'bz'
                                },
                                {
                                    xtype: 'hiddenfield',
                                    id: 'jszk',
                                    fieldLabel: 'Label',
                                    name: 'jzzk'
                                },
                                {
                                    xtype: 'hiddenfield',
                                    id: 'dldm',
                                    fieldLabel: 'Label',
                                    name: 'dldm'
                                },
                                {
                                    xtype: 'hiddenfield',
                                    id: 'ghdm1',
                                    fieldLabel: 'Label',
                                    name: 'ghdm'
                                },
                                {
                                    xtype: 'hiddenfield',
                                    id: 'gydm1',
                                    fieldLabel: 'Label',
                                    name: 'gydm'
                                },
                                {
                                    xtype: 'hiddenfield',
                                    id: 'gxdm',
                                    fieldLabel: 'Label',
                                    name: 'gxdm'
                                },
                                {
                                    xtype: 'hiddenfield',
                                    id: 'isPass1',
                                    fieldLabel: 'Label',
                                    name: 'isPass'
                                }
                            ],
                            dockedItems: [
                                {
                                    xtype: 'toolbar',
                                    x: 100,
                                    y: 490,
                                    dock: 'bottom',
                                    items: [
                                        {
                                            xtype: 'tbfill'
                                        },
                                        {
                                            xtype: 'button',
                                            handler: function(button, e) {
                                                var win = Ext.getCmp('zdxx_add1');
                                                win.close();
                                            },
                                            width: 80,
                                            text: '取消'
                                        },
                                        {
                                            xtype: 'tbspacer',
                                            width: 30
                                        },
                                        {
                                            xtype: 'button',
                                            handler: function(button, e) {


                                                Ext.Msg.confirm('提示',' 确认提交？注:提交成功后不可更改!', getResult);
                                                function getResult(confirm)
                                                {
                                                    console.log('confirm:', confirm);

                                                    if (confirm == "yes"){

                                                        var myform = Ext.getCmp('add_zdwidinfo1').getForm();
                                                        if (myform.isValid())
                                                        {
                                                            console.log('form is ava');
                                                            var title = Ext.getCmp('title1');
                                                            title.getTitle();
                                                            console.log(title.getTitle());



                                                            myform.submit({
                                                                // url : 'add_zdinfo',
                                                                success : function (form, action)
                                                                {
                                                                    Ext.Msg.alert('成功', '操作成功。');
                                                                    var mystore = Ext.StoreMgr.get('zd_infoStore'); //获得store对象
                                                                    //mystore.sort('id','DESC');
                                                                    mystore.reload();
                                                                    //             var isPass1 = Ext.getCmp('isPass1');
                                                                    //             console.log("isPass1:",isPass1);
                                                                    //             var record = mystore.findRecord('isPass',newValue);
                                                                    //             console.log(record);
                                                                    //             var isPass = record.get('isPass');
                                                                    //             console.log(isPass);

                                                                    var win = Ext.getCmp('zdxx_add1');
                                                                    win.close();

                                                                    var grid = Ext.getCmp('zd_info');
                                                                    grid.reconfigure(mystore);
                                                                    //var tab = Ext.getCmp('zdxx_tab');
                                                                    //tab.setActiveTab('committitle');




                                                                },
                                                                failure: function(form, action){
                                                                    Ext.Msg.alert('失败', '内容添加失败，请重试。');
                                                                }
                                                            });
                                                        }
                                                        else
                                                        {
                                                            Ext.Msg.alert('注意', '填写的信息有误，请检查！');
                                                        }

                                                    }
                                                }
                                            },
                                            id: 'addZdConfirm1',
                                            width: 80,
                                            text: '确定'
                                        }
                                    ]
                                }
                            ]
                        }
                    ],
                    listeners: {
                        activate: 'onTitle1Activate'
                    }
                },
                {
                    xtype: 'panel',
                    id: 'title2',
                    title: '未建成建设用地',
                    items: [
                        {
                            xtype: 'form',
                            autoScroll: true,
                            height: 302,
                            id: 'add_zdwidinfo2',
                            layout: 'absolute',
                            bodyPadding: 10,
                            title: '',
                            jsonSubmit: true,
                            url: 'add_zdinfo',
                            items: [
                                {
                                    xtype: 'textfield',
                                    x: 20,
                                    y: 510,
                                    hidden: true,
                                    width: 220,
                                    fieldLabel: '开发区名称',
                                    name: 'id'
                                },
                                {
                                    xtype: 'textareafield',
                                    x: 20,
                                    y: 160,
                                    width: 750,
                                    fieldLabel: '备注',
                                    name: 'bz'
                                },
                                {
                                    xtype: 'textfield',
                                    x: 20,
                                    y: 10,
                                    width: 220,
                                    fieldLabel: '开发区名称',
                                    name: 'kfqmc',
                                    allowBlank: false
                                },
                                {
                                    xtype: 'textfield',
                                    x: 285,
                                    y: 10,
                                    width: 220,
                                    fieldLabel: '图斑编号',
                                    name: 'tbbh',
                                    allowBlank: false
                                },
                                {
                                    xtype: 'combobox',
                                    x: 285,
                                    y: 130,
                                    width: 220,
                                    fieldLabel: '开发区评价范围',
                                    name: 'kfqpjfw',
                                    allowBlank: false,
                                    store: [
                                        '主区',
                                        '发展方向区'
                                    ]
                                },
                                {
                                    xtype: 'combobox',
                                    x: 550,
                                    y: 130,
                                    width: 220,
                                    fieldLabel: '开发区评价类型',
                                    name: 'kfqpjlx',
                                    allowBlank: false,
                                    store: [
                                        '工业主导型',
                                        '产城融合型'
                                    ]
                                },
                                {
                                    xtype: 'combobox',
                                    x: 550,
                                    y: 100,
                                    width: 220,
                                    fieldLabel: '地类名称',
                                    name: 'dlmc',
                                    store: [
                                        '已建成农村工矿仓储用地',
                                        '其他已建成农村建设用地',
                                        '已达到供地条件的其他用地',
                                        '未达到供地条件的其他土地'
                                    ],
                                    listeners: {
                                        change: 'onComboboxChange'
                                    }
                                },
                                {
                                    xtype: 'numberfield',
                                    x: 20,
                                    y: 130,
                                    width: 220,
                                    fieldLabel: '地类面积(公顷)',
                                    name: 'dlmj',
                                    emptyText: '0',
                                    hideTrigger: true
                                },
                                {
                                    xtype: 'combobox',
                                    x: 550,
                                    y: 10,
                                    width: 220,
                                    fieldLabel: '土地闲置情况',
                                    name: 'tdxzqk',
                                    allowBlank: false,
                                    store: [
                                        '是',
                                        '否'
                                    ]
                                },
                                {
                                    xtype: 'combobox',
                                    x: 20,
                                    y: 40,
                                    width: 220,
                                    fieldLabel: '权属',
                                    name: 'qs',
                                    allowBlank: false,
                                    store: [
                                        '国有',
                                        '集体'
                                    ]
                                },
                                {
                                    xtype: 'datefield',
                                    x: 285,
                                    y: 40,
                                    width: 220,
                                    fieldLabel: '供应时间',
                                    name: 'gysj',
                                    allowBlank: false,
                                    format: 'Y-m'
                                },
                                {
                                    xtype: 'combobox',
                                    x: 550,
                                    y: 40,
                                    width: 220,
                                    fieldLabel: '供应类型',
                                    name: 'gylx',
                                    store: [
                                        '划拨土地',
                                        '有偿使用且未到期土地',
                                        '有偿使用且已到期但未处置土地',
                                        '尚可划拨土地',
                                        '尚可供应工矿仓储用地',
                                        '其他尚可有偿使用土地'
                                    ],
                                    listeners: {
                                        change: 'onComboboxChange2'
                                    }
                                },
                                {
                                    xtype: 'combobox',
                                    x: 20,
                                    y: 70,
                                    width: 220,
                                    fieldLabel: '土地招拍佳情况',
                                    name: 'tdzpg',
                                    store: [
                                        '是',
                                        '否'
                                    ]
                                },
                                {
                                    xtype: 'textfield',
                                    x: 285,
                                    y: 70,
                                    width: 220,
                                    fieldLabel: '使用年限',
                                    name: 'synx'
                                },
                                {
                                    xtype: 'textfield',
                                    x: 550,
                                    y: 70,
                                    width: 220,
                                    fieldLabel: '土地使用者',
                                    name: 'tdsyz'
                                },
                                {
                                    xtype: 'combobox',
                                    x: 20,
                                    y: 100,
                                    width: 220,
                                    fieldLabel: '批准用途',
                                    name: 'pzyt',
                                    store: [
                                        '住宅用地',
                                        '工矿仓储用地',
                                        '街巷用地',
                                        '其他交通运输用地',
                                        '商服用地',
                                        '公园与绿地',
                                        '其他公共管理与公共服务用地',
                                        '其他城镇建设用地'
                                    ]
                                },
                                {
                                    xtype: 'combobox',
                                    x: 285,
                                    y: 100,
                                    width: 220,
                                    fieldLabel: '规划用途',
                                    name: 'ghyt',
                                    store: [
                                        '住宅用地',
                                        '工矿仓储用地',
                                        '街巷用地',
                                        '其他交通运输用地',
                                        '商服用地',
                                        '公园与绿地',
                                        '其他公共管理与公共服务用地',
                                        '其他城镇建设用地'
                                    ],
                                    listeners: {
                                        change: 'onComboboxChange3'
                                    }
                                },
                                {
                                    xtype: 'hiddenfield',
                                    id: 'jszk2',
                                    fieldLabel: 'Label',
                                    name: 'jzzk'
                                },
                                {
                                    xtype: 'hiddenfield',
                                    id: 'dldm1',
                                    fieldLabel: 'Label',
                                    name: 'dldm'
                                },
                                {
                                    xtype: 'hiddenfield',
                                    id: 'ghdm2',
                                    fieldLabel: 'Label',
                                    name: 'ghdm'
                                },
                                {
                                    xtype: 'hiddenfield',
                                    id: 'gydm2',
                                    fieldLabel: 'Label',
                                    name: 'gydm'
                                }
                            ],
                            dockedItems: [
                                {
                                    xtype: 'toolbar',
                                    x: 96,
                                    y: 517,
                                    dock: 'bottom',
                                    items: [
                                        {
                                            xtype: 'tbfill'
                                        },
                                        {
                                            xtype: 'button',
                                            handler: function(button, e) {
                                                var win = Ext.getCmp('zdxx_add1');
                                                win.close();
                                            },
                                            width: 80,
                                            text: '取消'
                                        },
                                        {
                                            xtype: 'tbspacer',
                                            width: 30
                                        },
                                        {
                                            xtype: 'button',
                                            handler: function(button, e) {




                                                Ext.Msg.confirm('提示',' 确认提交？注:提交成功后不可更改!', getResult);
                                                function getResult(confirm)
                                                {
                                                    console.log('confirm:', confirm);

                                                    if (confirm == "yes"){

                                                        var myform = Ext.getCmp('add_zdwidinfo2').getForm();
                                                        if (myform.isValid())
                                                        {
                                                            console.log('form is ava');
                                                            var title = Ext.getCmp('title2');
                                                            title.getTitle();
                                                            console.log(title.getTitle());
                                                            myform.submit({
                                                                // url : 'add_zdinfo',
                                                                success : function (form, action)
                                                                {
                                                                    Ext.Msg.alert('成功', '操作成功。');
                                                                    var mystore = Ext.StoreMgr.get('zd_infoStore'); //获得store对象
                                                                    mystore.reload();

                                                                    var win = Ext.getCmp('zdxx_add1');
                                                                    win.close();

                                                                    var grid = Ext.getCmp('zd_info');
                                                                    grid.reconfigure(mystore);

                                                                    //var tab = Ext.getCmp('zdxx_tab');
                                                                    //tab.setActiveTab('committitle');


                                                                },
                                                                failure: function(form, action){
                                                                    Ext.Msg.alert('失败', '内容添加失败，请重试。');
                                                                }
                                                            });
                                                        }
                                                        else
                                                        {
                                                            Ext.Msg.alert('注意', '填写的信息有误，请检查！');
                                                        }

                                                    }
                                                }
                                            },
                                            id: 'addZdConfirm2',
                                            width: 80,
                                            text: '确定'
                                        }
                                    ]
                                }
                            ]
                        }
                    ],
                    listeners: {
                        activate: 'onTitle2Activate'
                    }
                },
                {
                    xtype: 'panel',
                    id: 'title3',
                    title: '不可建成建设用地',
                    items: [
                        {
                            xtype: 'form',
                            autoScroll: true,
                            height: 231,
                            id: 'add_zdwidinfo3',
                            layout: 'absolute',
                            bodyPadding: 10,
                            title: '',
                            jsonSubmit: true,
                            url: 'add_zdinfo',
                            items: [
                                {
                                    xtype: 'textfield',
                                    x: 20,
                                    y: 510,
                                    hidden: true,
                                    width: 220,
                                    fieldLabel: '开发区名称',
                                    name: 'id'
                                },
                                {
                                    xtype: 'textareafield',
                                    x: 20,
                                    y: 100,
                                    width: 750,
                                    fieldLabel: '备注',
                                    name: 'bz'
                                },
                                {
                                    xtype: 'textfield',
                                    x: 20,
                                    y: 10,
                                    width: 220,
                                    fieldLabel: '开发区名称',
                                    name: 'kfqmc',
                                    allowBlank: false
                                },
                                {
                                    xtype: 'textfield',
                                    x: 290,
                                    y: 10,
                                    width: 220,
                                    fieldLabel: '图斑编号',
                                    name: 'tbbh',
                                    allowBlank: false
                                },
                                {
                                    xtype: 'combobox',
                                    x: 20,
                                    y: 40,
                                    width: 220,
                                    fieldLabel: '开发区评价范围',
                                    name: 'kfqpjfw',
                                    allowBlank: false,
                                    store: [
                                        '主区',
                                        '发展方向区'
                                    ]
                                },
                                {
                                    xtype: 'combobox',
                                    x: 290,
                                    y: 40,
                                    width: 220,
                                    fieldLabel: '开发区评价类型',
                                    name: 'kfqpjlx',
                                    allowBlank: false,
                                    store: [
                                        '工业主导型',
                                        '产城融合型'
                                    ]
                                },
                                {
                                    xtype: 'combobox',
                                    x: 550,
                                    y: 40,
                                    width: 220,
                                    fieldLabel: '地类名称',
                                    name: 'dlmc',
                                    store: [
                                        '河湖及其蓄滞洪区土地',
                                        '自然、生态保护区土地',
                                        '其他不可建设土地'
                                    ],
                                    listeners: {
                                        change: 'onComboboxChange1'
                                    }
                                },
                                {
                                    xtype: 'numberfield',
                                    x: 20,
                                    y: 70,
                                    width: 220,
                                    fieldLabel: '地类面积(公顷)',
                                    name: 'dlmj',
                                    emptyText: '0',
                                    hideTrigger: true
                                },
                                {
                                    xtype: 'combobox',
                                    x: 550,
                                    y: 10,
                                    width: 220,
                                    fieldLabel: '权属',
                                    name: 'qs',
                                    allowBlank: false,
                                    store: [
                                        '国有',
                                        '集体'
                                    ]
                                },
                                {
                                    xtype: 'combobox',
                                    x: 290,
                                    y: 70,
                                    width: 220,
                                    fieldLabel: '供应类型',
                                    name: 'gylx',
                                    emptyText: '不可供应土地',
                                    store: [
                                        '不可供应土地'
                                    ],
                                    listeners: {
                                        change: 'onComboboxChange4'
                                    }
                                },
                                {
                                    xtype: 'textfield',
                                    x: 550,
                                    y: 70,
                                    width: 220,
                                    fieldLabel: '认定依据',
                                    name: 'rdyj',
                                    allowBlank: false
                                },
                                {
                                    xtype: 'hiddenfield',
                                    id: 'jszk3',
                                    fieldLabel: 'Label',
                                    name: 'jzzk',
                                    submitValue: false
                                },
                                {
                                    xtype: 'hiddenfield',
                                    id: 'dldm2',
                                    fieldLabel: 'Label',
                                    name: 'dldm'
                                },
                                {
                                    xtype: 'hiddenfield',
                                    id: 'gydm3',
                                    fieldLabel: 'Label',
                                    name: 'gydm'
                                }
                            ],
                            dockedItems: [
                                {
                                    xtype: 'toolbar',
                                    x: 96,
                                    y: 517,
                                    dock: 'bottom',
                                    items: [
                                        {
                                            xtype: 'tbfill'
                                        },
                                        {
                                            xtype: 'button',
                                            handler: function(button, e) {
                                                var win = Ext.getCmp('zdxx_add1');
                                                win.close();
                                            },
                                            width: 80,
                                            text: '取消'
                                        },
                                        {
                                            xtype: 'tbspacer',
                                            width: 30
                                        },
                                        {
                                            xtype: 'button',
                                            handler: function(button, e) {


                                                Ext.Msg.confirm('提示',' 确认提交？注:提交成功后不可更改!', getResult);
                                                function getResult(confirm)
                                                {
                                                    console.log('confirm:', confirm);

                                                    if (confirm == "yes"){

                                                        var myform = Ext.getCmp('add_zdwidinfo3').getForm();
                                                        if (myform.isValid())
                                                        {
                                                            console.log('form is ava');
                                                            var title = Ext.getCmp('title3');
                                                            var title3=title.getTitle();
                                                            console.log(title3);


                                                            // console.log(title3);

                                                            myform.submit({
                                                                // url : 'add_zdinfo',
                                                                success : function (form, action)
                                                                {
                                                                    //执行通过或拒绝

                                                                    Ext.Msg.alert('成功', '操作成功。');
                                                                    var mystore = Ext.StoreMgr.get('zd_infoStore'); //获得store对象
                                                                    mystore.reload();

                                                                    var win = Ext.getCmp('zdxx_add1');
                                                                    win.close();

                                                                    var grid = Ext.getCmp('zd_info');
                                                                    grid.reconfigure(mystore);

                                                                    //var tab = Ext.getCmp('zdxx_tab');
                                                                    //tab.setActiveTab('committitle');


                                                                },
                                                                failure: function(form, action){
                                                                    Ext.Msg.alert('失败', '操作失败，请重试。');
                                                                }

                                                            });

                                                        }
                                                        else
                                                        {
                                                            Ext.Msg.alert('注意', '填写的信息有误，请检查！');
                                                        }
                                                    }
                                                }

                                            },
                                            id: 'addZdConfirm3',
                                            width: 80,
                                            text: '确定'
                                        }
                                    ]
                                }
                            ]
                        }
                    ],
                    listeners: {
                        activate: 'onTitle3Activate'
                    }
                }
            ]
        }
    ],
    listeners: {
        afterrender: 'onAdd_zdinfoAfterRender'
    },

    onDlmcChange: function(field, newValue, oldValue, eOpts) {
        var dlmc = Ext.getCmp('dlmc').getValue();
        console.log("dlmc:",dlmc);
        var store = Ext.StoreMgr.get('staKfqConstructStore'); //获得store对象
        console.log("store:",store);
        console.log(store.getCount());
        //store.filter('dlmc',newValue);
        var record = store.findRecord('dlmc',newValue);
        console.log(record);
        var dm = record.get('dldm');
        console.log(dm);
        var dldm = Ext.getCmp('dldm');
        dldm.setValue(dm);
        // store.load({
        //     params :{
        //         searchKeyword : newValue
        //     },callback: function(records, operation, success) {
        //         //         for(var index in records){
        //         //             var dldm = records[index].get('dldm');
        //         //             var weightValue = recordWeight.get(key);
        //         //             var idealValue = recordIdeal.get(key);
        //         //             var standardValue = 0;
        //         //             if(idealValue){
        //         //                 standardValue = weightValue/idealValue*100;
        //         //             }
        //         //             recordIdeal.set(key,standardValue);
        //         //             //console.log(weightValue+'/'+idealValue+'='+standardValue,key);
        //         //         }
        //         //         form.loadRecord(recordIdeal);

        //         var dldmvalue = records[0].get('dldm');
        //         var dldm = Ext.getCmp('dldm');
        //         dldm.setValue(dldmvalue);
        //         console.log("dldmvalue:",dldmvalue);
        //         console.log("dldm:",dldm);
        //     }
        // });
    },

    onGylxChange: function(field, newValue, oldValue, eOpts) {
        var gylx = Ext.getCmp('gylx').getValue();
        console.log("gylx:",gylx);
        var store = Ext.StoreMgr.get('staKfqConstructStore'); //获得store对象
        console.log("store:",store);
        console.log(store.getCount());
        //store.filter('dlmc',newValue);
        var record = store.findRecord('dlmc',newValue);
        console.log(record);
        var dm = record.get('dldm');
        console.log(dm);
        var ghdm = Ext.getCmp('gydm1');
                 ghdm.setValue(dm);
    },

    onComboboxChange5: function(field, newValue, oldValue, eOpts) {
        //var ghyt = Ext.getCmp('ghyt').getValue();
        //console.log("ghyt:",ghyt);
        var store = Ext.StoreMgr.get('staKfqConstructStore'); //获得store对象
        console.log("store:",store);
        console.log(store.getCount());
        //store.filter('dlmc',newValue);
        var record = store.findRecord('dlmc',newValue);
        console.log(record);
        var dm = record.get('dldm');
        console.log(dm);
        var ghdm = Ext.getCmp('gxdm');
                 ghdm.setValue(dm);
    },

    onGhytChange: function(field, newValue, oldValue, eOpts) {
        //var ghyt = Ext.getCmp('ghyt').getValue();
        //console.log("ghyt:",ghyt);
        var store = Ext.StoreMgr.get('staKfqConstructStore'); //获得store对象
        console.log("store:",store);
        console.log(store.getCount());
        //store.filter('dlmc',newValue);
        var record = store.findRecord('dlmc',newValue);
        console.log(record);
        var dm = record.get('dldm');
        console.log(dm);
        var ghdm = Ext.getCmp('ghdm1');
                 ghdm.setValue(dm);
    },

    onTitle1Activate: function(component, eOpts) {
        var jzzk = Ext.getCmp('jszk');
        var title = Ext.getCmp('title1');
        jzzk.setValue(title.getTitle());
        console.log(title.getTitle());
        console.log("jzzk:",jzzk.getValue());

    },

    onComboboxChange: function(field, newValue, oldValue, eOpts) {
        //var dlmc = Ext.getCmp('dlmc').getValue();
        //console.log("dlmc:",dlmc);
        var store = Ext.StoreMgr.get('staKfqConstructStore'); //获得store对象
        console.log("store:",store);
        console.log(store.getCount());
        //store.filter('dlmc',newValue);
        var record = store.findRecord('dlmc',newValue);
        console.log(record);
        var dm = record.get('dldm');
        console.log(dm);
        var dldm = Ext.getCmp('dldm1');
                 dldm.setValue(dm);
        // store.load({
        //     params :{
        //         searchKeyword : dlmc
        //     },callback: function(records, operation, success) {
        //         //         for(var index in records){
        //         //             var dldm = records[index].get('dldm');
        //         //             var weightValue = recordWeight.get(key);
        //         //             var idealValue = recordIdeal.get(key);
        //         //             var standardValue = 0;
        //         //             if(idealValue){
        //         //                 standardValue = weightValue/idealValue*100;
        //         //             }
        //         //             recordIdeal.set(key,standardValue);
        //         //             //console.log(weightValue+'/'+idealValue+'='+standardValue,key);
        //         //         }
        //         //         form.loadRecord(recordIdeal);
        //         var dldmvalue = records[0].get('dldm');
        //         var dldm = Ext.getCmp('dldm1');
        //         dldm.setValue(dldmvalue);
        //         console.log("dldmvalue:",dldmvalue);
        //         console.log("dldm:",dldm);
        //     }
        // });
    },

    onComboboxChange2: function(field, newValue, oldValue, eOpts) {
        //var gylx = Ext.getCmp('gylx').getValue();
        //console.log("gylx:",gylx);
        var store = Ext.StoreMgr.get('staKfqConstructStore'); //获得store对象
        console.log("store:",store);
        console.log(store.getCount());
        //store.filter('dlmc',newValue);
        var record = store.findRecord('dlmc',newValue);
        console.log(record);
        var dm = record.get('dldm');
        console.log(dm);
        var ghdm = Ext.getCmp('gydm2');
                 ghdm.setValue(dm);
    },

    onComboboxChange3: function(field, newValue, oldValue, eOpts) {
        //var ghyt = Ext.getCmp('ghyt').getValue();
        //console.log("ghyt:",ghyt);
        var store = Ext.StoreMgr.get('staKfqConstructStore'); //获得store对象
        console.log("store:",store);
        console.log(store.getCount());
        //store.filter('dlmc',newValue);
        var record = store.findRecord('dlmc',newValue);
        console.log(record);
        var dm = record.get('dldm');
        console.log(dm);
        var ghdm = Ext.getCmp('ghdm2');
                 ghdm.setValue(dm);
    },

    onTitle2Activate: function(component, eOpts) {
        var jzzk = Ext.getCmp('jszk2');
        var title = Ext.getCmp('title2');
         jzzk.setValue(title.getTitle());
            console.log(title.getTitle());
        console.log("jzzk:",jzzk.getValue());

    },

    onComboboxChange1: function(field, newValue, oldValue, eOpts) {
        //var dlmc = Ext.getCmp('dlmc').getValue();
        //console.log("dlmc:",dlmc);
        var store = Ext.StoreMgr.get('staKfqConstructStore'); //获得store对象
        console.log("store:",store);
        console.log(store.getCount());
        //store.filter('dlmc',newValue);
        var record = store.findRecord('dlmc',newValue);
        console.log(record);
        var dm = record.get('dldm');
        console.log(dm);
        var dldm = Ext.getCmp('dldm2');
                 dldm.setValue(dm);
        // store.load({
        //     params :{
        //         searchKeyword : dlmc
        //     },callback: function(records, operation, success) {
        //         //         for(var index in records){
        //         //             var dldm = records[index].get('dldm');
        //         //             var weightValue = recordWeight.get(key);
        //         //             var idealValue = recordIdeal.get(key);
        //         //             var standardValue = 0;
        //         //             if(idealValue){
        //         //                 standardValue = weightValue/idealValue*100;
        //         //             }
        //         //             recordIdeal.set(key,standardValue);
        //         //             //console.log(weightValue+'/'+idealValue+'='+standardValue,key);
        //         //         }
        //         //         form.loadRecord(recordIdeal);
        //         var dldmvalue = records[0].get('dldm');
        //         var dldm = Ext.getCmp('dldm2');
        //         dldm.setValue(dldmvalue);
        //         console.log("dldmvalue:",dldmvalue);
        //         console.log("dldm:",dldm);
        //     }
        // });
    },

    onComboboxChange4: function(field, newValue, oldValue, eOpts) {
        var gylx = Ext.getCmp('gylx').getValue();
        console.log("gylx:",gylx);
        var store = Ext.StoreMgr.get('staKfqConstructStore'); //获得store对象
        console.log("store:",store);
        console.log(store.getCount());
        //store.filter('dlmc',newValue);
        var record = store.findRecord('dlmc',newValue);
        console.log(record);
        var dm = record.get('dldm');
        console.log(dm);
        var ghdm = Ext.getCmp('gydm3');
                 ghdm.setValue(dm);
    },

    onTitle3Activate: function(component, eOpts) {
        var jzzk = Ext.getCmp('jszk3');
        var title = Ext.getCmp('title3');
         jzzk.setValue(title.getTitle());
            console.log(title.getTitle());
        console.log("jzzk:",jzzk.getValue());

    },

    onAdd_zdinfoAfterRender: function(component, eOpts) {
        // var title=this.getTitle();
        // var form=Ext.getCmp('add_zdwidinfo').getForm();
        // var button=Ext.getCmp('addZdConfirm');
        //  console.log(form.url);
        // if(title=="查看宗地信息")
        //     {
        //         button.setHidden(true);
        //     }
        // if(title=="修改宗地信息")
        // {
        //     form.url='upload_zdinfo';
        // }
        // if(title=="添加宗地信息")
        // {
        //     form.url='add_zdinfo';
        //     console.log(form.url);
        // }
    }

});